### ISSUE TITLE
std::chrono duration formatting doesn't follow ISO rules

### ISSUE THREAD

**Issue by DanielaE** [fmtlib/fmt#1003]
There are ISO rules regarding the [formatting of quantities based on SI units](https://en.wikipedia.org/wiki/International_System_of_Units#Lexicographic_conventions): [ISO31-0](https://en.wikipedia.org/wiki/ISO_31-0) superseeded by [ISO 80000-1](https://en.wikipedia.org/wiki/ISO_80000-1). More on that in [this PDF document](https://web.archive.org/web/20170814094625/http://www.bipm.org/utils/common/pdf/si_brochure_8_en.pdf), chapter 5.3.3 "Formatting the value of a quantity". The related [NIST page](https://physics.nist.gov/cuu/Units/rules.html) is currently down.

At present, a duration of f.e. one millisecond is formatted as "1ms" which is wrong according to the formatting rules: there must be a space (or possibly a Unicode half width space) between the numerical value and the unit. The non-standard formatting is hardcoded and is therefore out of control by users. This should be changed such that

- either the hardcoded formatting follows the rules
- or the default formatting follows the rules and there are some means for users to override the formatting in a non-standard way

**Comment by mwinterb** [comment]
The default rules were suggested to follow what `operator<<` will do in C++20, which has no space: https://en.cppreference.com/w/cpp/chrono/duration/operator_ltlt. My rationale with that suggestion was because it would happen "by magic" when C++20 is released and `fmt/ostream.h` is included.
Interestingly, an earlier proposal (which I don't think he ever submitted) by Howard did include a space. https://howardhinnant.github.io/duration_io/chrono_io.html
I'm currently skimming p0355 to see if there is rationale, but it doesn't seem like it. I wonder if @HowardHinnant would be able to offer insight if the divergence was on purpose.

**Comment by HowardHinnant** [comment]
`%q` and `%Q` are unused flags in the chrono format/parse flag set.  Perhaps `%Q` could represent a duration's value and  `%q` could be a flag for the unit abbreviation (in this case `ms`).  This would lead to client syntax like:
```
format("{:%Q %q}", d);
```
disclaimer:  Not implemented, or even fully thought through.

**Comment by vitaut** [comment]
I think matching the literal syntax is a nice property. It should be fine for logging and similar use cases. As for more user-facing use cases, following the ISO rules is probably not enough, because one would probably also want localization. In this case introducing format specifiers to represent duration value and unit as suggested by Howard is a good path forward.

**Comment by DanielaE** [comment]
Thanks Howard! If you are going to mull over this, please have a look at #1004, too. I am having a hard time to give a precision when formatting a a `std::chrono::duration<double>`, i.e. with floating-point representation types. As an avid user of `std::chrono` and `date`, my codebase has tons of various duration types, both with integral representation types (f.e. for timer registers of various bit widths and clock resolutions in diefferent clock domains of FPGAs or embedded processors) and floating point representation types (typically the user-facing stuff). The same is true for my timepoint types of which hardly anyone has the same epoch.
