### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by medithe** [fmtlib/fmt#1111]
Hi, 
I just wanted to ask, when a new version of fmtlib will be released.
Currently there are many new improvements since the last release.
Thx

**Comment by vitaut** [comment]
In a couple of months since floating point needs more work and I'm super busy with standardization at the moment.

BTW thanks for your work on {fmt}. Could you please review the updated [CONTIBUTING](https://github.com/fmtlib/fmt/blob/ebec00138bd10e949ff34955bcb096387cd32acc/CONTRIBUTING.md) document, particularly the part about licensing, and let me know if you agree with it being applied to your contributions to {fmt}? The library is likely to be relicensed (#1073) so I'm collecting approval from all earlier contributors.
