### ISSUE TITLE
Permit compile time validation for named arguments

### ISSUE THREAD

**Issue by acmorrow** [fmtlib/fmt#1195]
Compile time validation of named arguments is currently disallowed:

https://github.com/fmtlib/fmt/blob/f5f3ffac5908d167d2352ff1881753fa92e5bc34/include/fmt/format.h#L2210

That is a somewhat unfortunate restriction. I haven't dug into the internals of fmtlib enough to know whether this is due to the impossibility of making it work, or due to an implementation challenge. If the latter, I think it is probably worth figuring out how to make it work.

Is there some background on why it is currently disallowed? Any thoughts on whether an implementation is possible?

**Comment by vitaut** [comment]
> Is there some background on why it is currently disallowed?

Just because nobody has implemented it yet =).

> Any thoughts on whether an implementation is possible?

I think it should be possible to do in a way similar to handling compile-time format strings https://github.com/fmtlib/fmt/blob/40779749ac577e64084f2b80e89df88543f291ec/include/fmt/format.h#L3643 e.g. making `_a` UDL return an argument with a compile-time name, collecting them in an array and using that for lookups when parsing the format string. It is impossible to do with the `fmt::arg` API.

**Comment by vitaut** [comment]
I think it's not worth doing until we have a better mechanism than a UDL hack (e.g. `constexpr` parameters).
