### ISSUE TITLE
Windows 10 RS4 supports locale ".utf8" already, I wonder why `setlocale` doesn't make fmt::print with L-string work?

### ISSUE THREAD

**Issue by denchat** [fmtlib/fmt#1229]
Now we can do this `std` way on Windows 10 v1803 or later
````
std::setlocale(LC_ALL, "en_US.utf8");
wprintf(L"zß水");
````
but `fmt::print` still do need this :
````
_setmode( _fileno(stdout), _O_WTEXT );
````
Otherwise, it only prints 'z'.

I wonder why?  Is there some performance hits to support `setlocale` like `wprintf`?

**Comment by denchat** [comment]
I just realize this works with out `_setmode`
````
fmt::print(std::wcout,L"zß水\n");
````

Shouldn't `fmt::print` select `wcout` seemlessly?  Why?

**Comment by vitaut** [comment]
> I wonder why?

As a library function `print` shouldn't be changing the global locale, because this could mess up user assumptions. This should be done on the application level.

> Shouldn't `fmt::print` select `wcout` seemlessly?

Last time I checked writing via iostreams added nontrivial overhead. But you can easily write a formatting function that writes to `wcout` instead of `stdout` by default yourself.
