### ISSUE TITLE
Cannot specialize fmt::formatter<T> if basic_string_view is constructible from T

### ISSUE THREAD

**Issue by puetzk** [fmtlib/fmt#1378]
Microsoft has a wrapper around their COM BSTR string type called [`_bstr_t`](https://docs.microsoft.com/en-us/cpp/cpp/bstr-t-class?view=vs-2019). Somewhat inadvisably, but typically for early C++, [it has implicit conversion operators to `char*` and `wchar_t *`](https://docs.microsoft.com/en-us/cpp/cpp/bstr-t-wchar-t-star-bstr-t-char-star?view=vs-2019).

However, the conversion implicit conversion to and from `char *` is rather ill-advised in most circumstances; it does an encoding conversion from the locale-dependent `CP_ACP`.

So I thought I could just specialize to this and it would be more-specific:

```
namespace fmt {
	template <>
	struct formatter<_bstr_t> {
		template <typename ParseContext>
		constexpr auto parse(ParseContext &ctx) { return ctx.begin(); }

		template <typename FormatContext>
		auto format(const _bstr_t &s, FormatContext &ctx) {
			return format_to(ctx.out(), string_cast<std::string,encoding::utf8>(s));
		}
	};
}
```

However, that fails with 

>'fmt::v6::internal::arg_mapper<Context>::map': ambiguous call to overloaded function
>        with
>        [
>            Context=fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>,char>
>        ]
>...\.conan\data\fmt\6.0.0\_\_\package\b786e9ece960c3a76378ca4d5b0d0e922f4cedc1\include\fmt\core.h(828): note: could be 'const T &fmt::v6::internal::arg_mapper<Context>::map<T,0>(const T &)'
>        with
>        [
>            T=_bstr_t,
>            Context=fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>,char>
>        ]
>...\.conan\data\fmt\6.0.0\_\_\package\b786e9ece960c3a76378ca4d5b0d0e922f4cedc1\include\fmt\core.h(793): note: or       'fmt::v6::basic_string_view<char> fmt::v6::internal::arg_mapper<Context>::map<T,0>(const T &)'
>        with
>        [
>            Context=fmt::v6::basic_format_context<std::back_insert_iterator<fmt::v6::internal::buffer<char>>,char>,
>            T=_bstr_t
>        ]
>...\.conan\data\fmt\6.0.0\_\_\package\b786e9ece960c3a76378ca4d5b0d0e922f4cedc1\include\fmt\core.h(844): note: while trying to match the argument list '(T)'
>        with
>        [
>            T=_bstr_t
>        ]

Because both 

https://github.com/fmtlib/fmt/blob/7512a55aa3ae309587ca89668ef9ec4074a51a1f/include/fmt/core.h#L789-L795

and
https://github.com/fmtlib/fmt/blob/7512a55aa3ae309587ca89668ef9ec4074a51a1f/include/fmt/core.h#L824-L830

are equally-specific partial specializations whose enable_if was satisfied.

Did I miss something, or is there no way to specify a formatter for something already convertible to `char *` (but not in the desired format)?

**Comment by tt4g** [comment]
You can use proxy class if it is due to an implicit conversion.

For example:

```cpp
struct bstrProxy
{
    const _bstr_t &bstr;
};

namespace fmt {
    template <>
    struct formatter<bstrProxy> {
        template <typename ParseContext>
        constexpr auto parse(ParseContext &ctx) { return ctx.begin(); }

        template <typename FormatContext>
        auto format(const bstrProxy &proxy, FormatContext &ctx) {
            return format_to(ctx.out(), return format_to(ctx.out(), string_cast<std::string,encoding::utf8>(proxy.bstr)););
        }
    };
}
```

**Comment by puetzk** [comment]
Yep, that would work to diambiguate (or just cast it before passing to `fmt::format`

I just found it odd that an explicit specialization of fmt::formatter with no conversions doesn't take precedence over an implicit conversion to char *. I.e. that the enable_if doesn't include `!has_formater` like enums do, so that specialization of the `formatter` inhibits map turning them into `int` (or in this case into `basic_string_view`):

https://github.com/fmtlib/fmt/blob/7512a55aa3ae309587ca89668ef9ec4074a51a1f/include/fmt/core.h#L819-L820

**Comment by puetzk** [comment]
Yes, they are implicit, which makes `std::is_constructible<basic_string_view<char_type>, T>::value` true (you can implicitly convert to `char*`, then construct basic_string_view from that).
`std::is_constructible` considers the `basic_string_view` constructor explicit, so this is only one user-defined conversion and is legal.

> This may cause an implicit conversion when it becomes an argument to format function

It did not do that, the ambiguity is between the two specializations of `arg_mapper::map`, which can't decide whether to decay it to `basic_string_view` or keep it `T` and use the specialized formatter.

**Comment by puetzk** [comment]
As a draft to clarify the ambiguity I'm talking about, see 6ad6ef371bf1042f04e83316ae343288b05f2b60.

I'm not sure about has_fallback_formatter, but it seems to be for using `operator <<(std::ostream)` overloads, and its seems like those are also more formatting-specific than a conversion to `char *`. And the is_enum cases work that way, so I followed that pattern.

**Comment by tt4g** [comment]
> > This may cause an implicit conversion when it becomes an argument to format function
> 
> It did not do that, the ambiguity is between the two specializations of `arg_mapper::map`, which can't decide whether to decay it to `basic_string_view` or keep it `T` and use the specialized formatter.

@puetzk  Your opinion is correct. Implicit conversion occurs in SFINAE and there seems to be an ambiguous specialization of the template.

**Comment by DBJDBJ** [comment]
Perhaps...
            `using bstr_proxy_type = std::reference_wrapper< _bstr_t >  ;`

**Comment by puetzk** [comment]
I'm aware :snake: :airplane:. There are even some man-portable missiles if you need to shoot many feet at once (`_com_ptr<T>::operator &` that NULLs the instance, anyone?). I'm gradually modernizing legacy code :-).

There are lots of ways to avoid the problem I specifically had with `_bstr_t` (to start with the simplest, just convert it before input to `fmt::format`). I opened this issue because it seemed to point out a shortcoming in fmt that wasn't really specific to `bstr_t` (that you couldn't have custom formatter for anything constructible to string_view).

In some sense, both `foo::operator char *()` (or any other path to convert to `string_view`) and `fmt::formatter<foo>::format()` are user-specified conversions, so one *could* argue that defining both is a legitimate ambiguity. I just don't think you *should*, because it seems intuitive to give fmt::formatter like the preference, and its more capable (e.g. might support parse() to control exactly how the `foo` gets formatted, like `int`, `tm`, etc all do). So it seems that even a type being designed from scratch could reasonable have generic conversion to `string_view`, yet also a more-specific `formatter<T>`. And you can't currently do that because it makes `arg_mapper::map` ambiguous (overlapping SFINAE).

**Comment by DBJDBJ** [comment]
Well, there is this ancient school of philosophy that claims: "nothing must break encapsulation and decoupling" ... 
```cpp
  fmt::print(" Hey Ma, Look: { } !", _bstr_t_instance ) ;
```
They go as far as claiming above breaks both in one go, for `type_x` ... I am sure they would advise on this course of action:
```cpp
   fmt::printf("Hey, Ma, look: { }!",   my_simple_conversions::to_string( _bstr_t_instance ) ) ;
```
Silly people ...

**Comment by puetzk** [comment]
OK, so where does this stand? Leaving aside the somewhat odious nature of `_bstr_t` in particular and the wide variety of possible workarounds...

Any type that has both a specizlied `fmt::format<T>` and `std::is_constructible<string_view,T>` causes ambiguous SFINAE in arg_mapper::map. Is this a bug that should be fixed by giving one of them precedence? I think `fmt::format<T>` is the obvious preference, since it's tightly associated to fmt and supports more features like additional flags, but do you agree, or is working as you intended (i.e. you think it's not to pick one over the other and it should indeed fail as ambiguous).

It's easy to fix the SFINAE (I can make a PR), just curious how to proceed.

**Comment by DBJDBJ** [comment]
@puetzk assuming your code will not be discarded in a few month's time, I might advise using N4835 aka C++20. One could assume that is a relevant `<format>` spec.

One might also assume `std::format` will **not** be changed because of `_bstr_t` issues that are easy to fix with the right amount of `SFINAE`, secret sauce.

Let's assume that assumption is right.  And you are gradually changing the legacy code (Visual Studio  + COM, I assume again) ... In that case I might be o bold to ask why not just casting `_bstr_t` instance to `std::wstring` and the `std::format` it?

```cpp
     _bstr_t  bstr(L"The COM string");
     std::wstring ws{  ( (wchar_t *)bstr } ;
     // fmt::print is not C++20 but who cares
    fmt::print("{ }" , ws ) ;
```
this is all in case you really (really) do not want to use cppwinrt ...

**Comment by vitaut** [comment]
In the case of `_bstr_t` a proxy class should be used because you shouldn't define `formatter` specializations for types that you don't own. If it was a class that you own then I'd recommend either not using implicit conversion to `const char*` or leaving it formattable as a string. If the type is not string-like it shouldn't be convertible to `const char*` in the first place.

**Comment by puetzk** [comment]
Thanks for a conclusion, and sorry if I was not being clear. I've already fixed my specific issue with _bstrt_t (by casting it to a better-behaved type before the call to `fmt::format`. I was just trying close out my issue here with a decision between "no type is allowed to have have both an explicit conversion to string_view and a customized formatter" or "that ambiguity in arg_mapper is a bug and should be fixed", rather than leaving an open-and-undecided issue to clutter your tracker.

Thanks @DBJDBJ for your input. I don't disagree with anything you said in principle, but cppwinrt does not help (its string type also includes conversion to string_view). And C++20/P0645R10 (https://fmt.dev/Text%20Formatting.html#format.formatter) makes no mention of anything like the arg_mapper::map, so that seemed an implementation optimization not actually called for (or prohibited) in the standard. So I still felt there was a question to be answered here (and maybe a PR to write if fixing the ambiguity was desired) before I moved on :-)

**Comment by DBJDBJ** [comment]
Truth to be told, c++winrt seems in some very (very) curious space ... both technically and politically inside MSFT. 

Things went from "Hey Everybody, Let's do C++17 + cppwinrt!" to the spiritual leader all of a sudden doing Rust ?!

**Comment by nick42** [comment]
Question on this issue:

This is obviously an issue with anything which implicitly converts to `const wchar_t*`. In particular, as noted in other places, this breaks the ability to provide an explicit specialization for CString.

I don't pretend to know all the specifics about how or why the implementation does what it does, but the current suggested workaround seems to be "stay on v5". Is that going to be the message for anyone using any string-type wrapper classes? Should I plan to be on v5 effectively forever?

**Comment by vitaut** [comment]
The suggestion is to wrap types with problematic conversions and use the usual extension API if you need custom formatting. No need to stay on v5.

**Comment by nick42** [comment]
No offense, but that's sorta infeasible for any sort of large project. I probably have upwards of 100k+ instances of using CString as a string parameter in a fmt call, and I don't think I can justify replacing every instance with a proxy wrapper construction. I guess I'll just hope this is addressed with the std::format implementation.

**Comment by vitaut** [comment]
CString is a string type despite its numerous problems. Is there any reason why you don't want it formatted as a string?

**Comment by nick42** [comment]
I absolutely do want it formatted as a string. With v5 it was working, via an explicit specialization (which just essentially extracted the raw string). With v6, that conversion is ambiguous, with or without the explicit specialization, as per the problem at the beginning of this thread. I don't want to add a proxy constructor wrapper in the 100k+ places in the code where I pass it as a string parameter to a formatting function.

**Comment by DBJDBJ** [comment]
> I probably have upwards of 100k+ instances of using CString as a string parameter in an fmt call

Which "fmt call" would that be?

**Comment by vitaut** [comment]
> I absolutely do want it formatted as a string.

Could you elaborate how do you want it to be formatted?

**Comment by nick42** [comment]
Sure. My "typical" use-case comes from replacing printf-style string formatting with fmt a few years ago, by replacing the underlying calls (and converting my interstitial layer to variadic template methods, instead of the C-style variable-arguments mechanism). As you probably know, despite its "numerous problems", CString is written so that it can be passed directly as a string parameter to a C-style printf call, and that works by-design.

Pseudo-code to illustrate my use-case:

    CString value(L"world");
    auto result = sprintf_using_fmt(L"Hello %s!", value);
    // ... Internally, this calls fmt::sprintf() in the interstitial layer

In v5, I wrote an override for the fmt::formatter struct to handle CString (actually two, for CStringA and CStringW, to be specific). In v6, this is generating an ambiguity error, with or without the override, as per the original issue. I do not see a method to resolve without modifying every call location (although perhaps I'm missing something).

I don't need/want in particular style of non-standard formatting for the string; I just want the calls to compile/work as they did in v5. Hence my inquiry as to whether or not I could expect this to be resolved at some point, or whether I need to plan to just stay in v5 until I find an alternative.

**Comment by DBJDBJ** [comment]
If this is the signature of  `sprintf_using_fmt` 
```cpp
auto sprintf_using_fmt(  const wchar_t * , const wchar_t * );
```
Then base of `Cstring` aka `CSimpleStringTClass` implicit conversion operator will be used.

There is also an example [here](https://docs.microsoft.com/en-us/cpp/atl-mfc-shared/reference/csimplestringt-class?view=vs-2019#operator_pcxstr).

**Comment by nick42** [comment]
I suppose my over-simplification was too overly simplified to convey the point.

My actual interstitial method is approx this:

    template< class TResultType, typename TFormatString, typename... Arg >
    inline auto formatpf_to_Result( const TFormatString& tFormatString, Arg&&... args )
    {
        try
        {
            auto strString = fmt::sprintf( tFormatString, std::forward<Arg>( args )... );
            // Return the result, with some conversion handling
        }
        // catch, etc...
    }

Hope that helps clarify the use-case.

Also, just for reference, I haven't done extensive testing to determine the root cause, etc,; I googled the issue, and found this. The symptoms and effect seem to be the same (ie: CString has an implicit conversion operator, etc.). It's a regression in my use-case from v5, and it appears from the thread it will not be addressed. I'm mainly just trying to figure out my options moving forward.

**Comment by DBJDBJ** [comment]
I was afraid that would be the answer :)  Yes without extension mechanism working you would need basically to implement your own `sprintf` using a very similar design ...

I have no current knowledge of that. But. Why would `FMT` have an issue with that class is slightly puzzling? The base of CString is basically this:
```cpp
struct c_string_base {
   char data[0xFF]{}; 
  // implicit conversion
  operator const char * () () { return data} 
} ;
```
That should be trivial to make work with FMT.  Assuming it is, then CString type has some other  "feature", "getting in the way" ? 

HTH

**Comment by nick42** [comment]
Re MSVC, using VS2019, C++17, latest compiler, etc.

Re CString, it's actually quite a bit more complicated, owing to the "making C-style printf usage work" engineering feat; that's an interesting code splunk, if you're not familiar. That basic idea is the same as the _bstr_t example, though (ie: class with implicit conversion operator apparently confusing overloading within the library).

Re decoupling, I'm not sure what you mean. Your example wouldn't work as-written, at least without some additional code (to wit, compiler could not deduce the auto result type in the prototype without trailing type syntax, if the method is not defined in the header). I do have a reasonable amount of decoupling in my codebase, actually; for instance, the result type is dynamic, to allow for returning either the native fmt-generated type (ie: std::wstring), or an implicit conversion to the "standard" string wrapper in our codebase (ie: CString). Both usages are supported and used (in part, for migration where applicable and appropriate).

Anyway, hope that helps clarify some.

**Comment by vitaut** [comment]
I think it's reasonable to expect `formatter` specializations to take precedence over implicit conversions so I implemented the change in https://github.com/fmtlib/fmt/commit/b0e88b8be76e6277fd9173e7cab5cb31353d5fbf. I'd still recommend not doing it for classes you don't own but if it's done in a controlled environment (e.g. only in application code that is not used anywhere else) it's probably OK.

**Comment by vitaut** [comment]
So this will work (once https://github.com/fmtlib/fmt/commit/b0e88b8be76e6277fd9173e7cab5cb31353d5fbf is merged):

```c++
template <>
struct fmt::formatter<_bstr_t> : formatter<std::string> {
  auto format(const _bstr_t& s, format_context& ctx) {
    return formatter<std::string>::format(
      string_cast<std::string, encoding::utf8>(s), ctx);
  }
};
```
although not recommended.

**Comment by nick42** [comment]
That's all I'm looking for, I think. :)

I take your point, also: it would be "bad" to have specializations for classes I don't own that proliferated beyond my code base. That's certainly not my intent. In this case, I just want a way to resolve the ambiguity, and construct something inside the override which is compatible with what the fmt library wants to use anyway (in this case, probably a string_view directly).

**Comment by DBJDBJ** [comment]
@vitaut if you are not extra vigilant (me thinks) this whole ATL/MFC/_bstr_t issue might grow some serious weed in `{fmt}` ... Perhaps you want some form of decoupling from legacy code. 

I am not `{fmt}` social secretary but I would like to say:

1. `fmt::format` is `std::format` and is standard C++20.
2. `fmt::print` and the friends is open source code. 

Read between the lines. Hint: there are no support lines. This is my personal opinion.

**Comment by vitaut** [comment]
`formatter` having higher precedence than implicit conversions is consistent with the {fmt} design. It just happens to provide a solution for poorly designed APIs such as the ones of ATL/MFC/_bstr_t.

**Comment by DBJDBJ** [comment]
I am/was slightly worried you will start "servicing" the legacy ... Again, nobody is asking me but I will say it: guidance doc for legacy apps might come handy here. This thread has born a few good points on the subject.

**Comment by nick42** [comment]
FWIW, as an opinion of a user of the library...

I think the ability to support classes with implicit conversions to (presumably NULL-terminated strings via) raw character pointers in the library is a good thing. Third-party libraries is not the only place this comes up, even in my code (eg: I have a subclass of std::string_view for NULL-terminated strings, with a similar implicit operator).

There is a lot of printf-style formatting in existing codebases. Providing a path to migrate that slowly, and have it work in a more "safe" manner, is a good thing, and one of the most compelling arguments for adding {fmt} to a legacy project, imho. Migrating a large existing project wholesale to a new syntax is a non-starter, but providing alternative functions/syntax which calls the same underlying code and migrating usage slowly is very feasible.

I also think a conversion guide might be handy, both for legacy apps and for apps which are refactoring away from printf-style usage. To that end, some things which I have observed and/or dealt with in my codebase:

- CString::FormatV has special-case handling for NULL string values, replacing them with a constant string value ("(null)"), rather than causing an error. This is very useful, imho, and I implemented something similar for my usage of {fmt}.
- CString::FormatV (and sprintf, at least on Windows) has handling for "opposite width" character and string variables; that is, "%s" vs "%S". This I was not able to augment my usage of {fmt}, and had to modify my usage to work around. See: https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019

Anecdotally, what I ended up doing was writing a template function (called "ToFmtArg_s()" in my codebase), converting problematic instances to "%s" in the format string, and using the function to convert the argument. The function can then catch/handle special cases via normal template mechanics (SFINAE, etc.), and act as a pass-through for cases which are handled implicitly by the library. That's also where/how I added support for "(null)" replacement, and support a limited amount of automatic conversion, a la boost lexical_cast.
