### ISSUE TITLE
std::chrono duration floating point issues at compile time

### ISSUE THREAD

**Issue by leolchat** [fmtlib/fmt#1423]
It seems that `format("{:.2}", std::chrono::duration<double>(1.234))` works fine but `"{:.2}"_format(std::chrono::duration<double>(1.234))` doesn't, at least with release 6.0.0 and gcc 7.4.0 shipped with ubuntu 18.04

**Comment by vitaut** [comment]
That's expected. chrono formatter doesn't support compile-time checks (and therefore `_format`). Use the normal `fmt::format` instead.

**Comment by leolchat** [comment]
It is a little disturbing when everything is compile time to have the compile time check fail with really hard to read errors.

By closing the issue I assume it is not in scope to get fixed?

The documentation is pretty lacking concerning compile time checks and what can or cannot be done with it. It is a life saver when it works and when we can use it all the time.

**Comment by vitaut** [comment]
There are no plans to make chrono format string checks `constexpr` but a PR would be welcome.

**Comment by vitaut** [comment]
In general you can use compile-time checks for built-in and string types.

**Comment by leolchat** [comment]
Thanks for the clarification. Not sure I have time to dive in a PR like this one but who knows.

I was trying to find if `std::format` had a solution for compile time checks but there seems to be none for c++20, do you happen to know where this is headed?

**Comment by vitaut** [comment]
The design of `std::format` permits compile-time checks but due to the language limitations at the time of writing the proposal it's not yet exposed via the top-level API. Once `constexpr` parameters or parametric expressions make it into the standard it will be possible to have compile-time check via the intuitive API. Otherwise we'll have to continue using various hacks to pass compile-time strings.
