### ISSUE TITLE
implicit-fallthrough warning

### ISSUE THREAD

**Issue by federico-busato** [fmtlib/fmt#1459]
`g++ -std=c++14 -Wimplicit-fallthrough` shows potential fallthrough in `parse_float_type_spec`
https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L1227

`FMT_FALLTHROUGH` could be extended by using `[[gnu::fallthrough]]`

**Comment by vitaut** [comment]
Could you submit a PR extending `FMT_FALLTHROUGH` to use `[[gnu::fallthrough]]` when available?

**Comment by federico-busato** [comment]
I'm overcommitted with my job but I love this library. I try to see what I can do

**Comment by scamille** [comment]
Here is what we use at https://github.com/simulationcraft/simc . Unfortunately I am currently a bit time restricted as well, but might be able to do something in a couple weeks time. Otherwise feel free to adapt it to fmt :)

#if __cplusplus > 201402L && __has_cpp_attribute(fallthrough)
#  define SC_FALLTHROUGH [[fallthrough]]
#elif __has_cpp_attribute(gnu::fallthrough)
#  define SC_FALLTHROUGH [[gnu::fallthrough]]
#elif __has_cpp_attribute(clang::fallthrough)
#  define SC_FALLTHROUGH [[clang::fallthrough]]
#elif defined( _MSC_VER ) && _MSC_VER >= 1911 && _MSVC_LANG >= 201703L
#  define SC_FALLTHROUGH [[fallthrough]]
#else
#  define SC_FALLTHROUGH
#endif
