### ISSUE TITLE
Unexpected formatting of bool-convertible custom type

### ISSUE THREAD

**Issue by benoitryder** [fmtlib/fmt#1503]
If a custom type defines both `operator bool` and `operator<<`, it is formatted as `bool` instead of using the custom `operator<<`.
According to `git bisect`, behavior changed with ccc8f5d to fix #1316.

This seems to be the same issue as #247. (I don't know if the expected behavior changed since then.)

Example code ([Godbolt](https://godbolt.org/z/hWqJuh)):
```cpp
#define FMT_HEADER_ONLY
#include <fmt/ostream.h>

struct S {
    operator bool() const { return true; }
};

std::ostream& operator<<(std::ostream& os, S const&) { return os << "s-value"; }

int main() {
    fmt::print("s: {}\n", S{});
}
```
Prints `s: true` instead of `s: s-value`.

**Comment by vitaut** [comment]
I don't see a way to make this work without breaking a much more important fix of #1316. Since having an implicit conversion to `bool` is a bad idea in general, I recommend making it `explicit`. Alternatively you can provide a custom `formatter<S>`: https://fmt.dev/latest/api.html#formatting-user-defined-types
