### ISSUE TITLE
windows.h included when FMT_USE_WINDOWS_H=0

### ISSUE THREAD

**Issue by bowie7070** [fmtlib/fmt#1508]
I am using the header only version of fmt on windows and I am presently getting problems because format-inl.h includes windows.h even when FMT_USE_WINDOWS_H is defined to be 0. As far as I can tell the code in format-inl.h around line 26 is not checking the definition of FMT_USE_WINDOWS_H.

#ifdef _WIN32
#  include <io.h>
#  include <windows.h>
#endif

I'm checking out the latest version using the SVN interface to github so I get the following from svn info:

URL: https://github.com/fmtlib/fmt.git/trunk/include
Relative URL: ^/trunk/include
Repository Root: https://github.com/fmtlib/fmt.git
Repository UUID: e2afa68a-cdf3-33dd-4245-ce57b7db7bff
Revision: 6014
Node Kind: directory
Schedule: normal
Last Changed Author: victor.zverovich
Last Changed Rev: 6011
Last Changed Date: 2020-01-05 04:11:35 +1100 (Sun, 05 Jan 2020)

**Comment by vitaut** [comment]
That's expected: `windows.h` is used unconditionally in the implementation. You can use {fmt} as a static library (which is a recommended configuration) to avoid pulling in the implementation details.

**Comment by bowie7070** [comment]
Ah, I see. If possible, it might be helpful for there to be an error or a diagnostic when FMT_USE_WINDOWS_H defined to be 0 and is also defined FMT_HEADER_ONLY since this combination is not going to do what is hoped for. Thanks for the prompt response.

**Comment by dalboris** [comment]
But this is a regression, isn't it?

In 6.1.2, it seems possible to define both `FMT_USE_WINDOWS_H=0` and `FMT_HEADER_ONLY`, and have it do the expected thing, thanks to this actually super nice macro logic in `format-inl.h`:

```
#if FMT_USE_WINDOWS_H
#  if !defined(FMT_HEADER_ONLY) && !defined(WIN32_LEAN_AND_MEAN)
#    define WIN32_LEAN_AND_MEAN
#  endif
#  if defined(NOMINMAX) || defined(FMT_WIN_MINMAX)
#    include <windows.h>
#  else
#    define NOMINMAX
#    include <windows.h>
#    undef NOMINMAX
#  endif
#endif
```

But this logic was removed in https://github.com/fmtlib/fmt/commit/35959a31d7f58fe9f787649b4302944e9afe4024 , and then a new logic was added in https://github.com/fmtlib/fmt/commit/dac9a7f99dfbbd09a6a9c04480059f91e4eb3733 (see below), which isn't as smart and make it now impossible to not have `<windows.h>` in header-only mode:

```
#ifndef _WIN32
#  define FMT_USE_WINDOWS_H 0
#elif !defined(FMT_USE_WINDOWS_H)
#  define FMT_USE_WINDOWS_H 1
#endif
```

Is this change from "possible to not have windows.h in header-only mode" to "impossible to not have windows.h in header-only mode" intentional?

**Comment by dalboris** [comment]
(Sorry, I previously copy-pasted the wrong block, see edit of my previous post)

**Comment by vitaut** [comment]
> Is this change from "possible to not have windows.h in header-only mode" to "impossible to not have windows.h in header-only mode" intentional?

Yes, it is intentional. `windows.h` is used in the implementation and header-only mode pulls in implementation details into the header for obvious reasons.

**Comment by dalboris** [comment]
Thanks for the answer. But then, could you clarify what is the intended purpose of FMT_USE_WINDOWS_H? I assumed it was so that fmt wouldn't include window.h (and therefore disable all the utf8 and windows error stuff). This is *especially* important in the header-only mode, since you do want to pollute all your translation units with windows.h. I thought this was the main purpose of the flag. And in static/shared mode, if FMT_USE_WINDOWS_H does disable utf8 and windows error stuff (does it?), then why would the implementation need to include windows.h? I'm a bit confused.

Besides, just for information, I'm pretty sure this will break some code. When I first added {fmt} to my codebase in header-only mode, it did break my build on Windows, due to windows.h defining near/far macros which were used as identifiers in my code. There are also other possible issues with min/max. I can imagine a lot of people decided to define FMT_USE_WINDOWS_H specifically to fix these issues, and now when they will upgrade {fmt} to the next version, it will break again. This isn't my case as I have preferred to rename my near/far identifiers rather then defining FMT_USE_WINDOWS_H, but I can imagine other people doing differently.

Anyway, thank you for the amazing library and addition to C++20. I am super excited by this, it was a major pain point of C++.

**Comment by dalboris** [comment]
Note: there is the following comment in `os.h` (which was in `format.h` in 6.1.2):

```
// Define FMT_USE_WINDOWS_H to 0 to disable use of windows.h.
// All the functionality that relies on it will be disabled too.
```

So it does seem like the intended purpose of FMT_USE_WINDOWS_H was, at least at some point, to allow clients to disable the inclusion of `windows.h` (for obvious reason in my opinion: why would you want to include this if you don't need the added functionality?). So it seems strange that now, `windows.h` is included unconditionally, although I understand that you wouldn't want the maintenance burden of supporting the two configurations.

I would recommend either allow back the functionality to include `windows.h` conditionally (preferred for backward compatibility, but more work for you now and in the future), or otherwise removing the FMT_USE_WINDOWS_H flag entirely (simply use _WIN32) and add in the documentation a mention that when used in header-only mode on Windows, `format.h` includes `windows.h` (which would make it a compelling reason to compile it as a static or shared library instead).

As is, the behavior in the master branch is just very confusing. It seems like there is a way to disable inclusion of `windows.h`, while in fact there isn't. The confusion wasn't there in 6.1.2, since FMT_USE_WINDOWS_H was indeed doing what's written on the tin.

**Comment by dalboris** [comment]
(sorry for the spam)

After digging a little more for what was the rationale behind FMT_USE_WINDOWS_H (i.e., was it meant to be an implementation detail, or was it intended to be a public flag customizable by clients?), I found the following release note:

> https://github.com/fmtlib/fmt/releases/tag/2.0.0
>
> Added an option to disable use of windows.h when FMT_USE_WINDOWS_H is defined as 0 before including format.h (#171). Thanks to @alfps (Alf P. Steinbach).

The relevant commit is: https://github.com/fmtlib/fmt/commit/24c309fbfafc4339a084d450c36e0b9458ea25f4

In light of this, changing the inclusion of windows.h from conditional to unconditional does seem like a serious backward-incompatible breaking change.

**Comment by vitaut** [comment]
`FMT_USE_WINDOWS_H` is mostly legacy at this point and should probably be removed.

**Comment by vitaut** [comment]
You are right, it can be a breaking change if the user opted into header-only mode, opted into `FMT_USE_WINDOWS_H` and have code which is incompatible with `windows.h`.

**Comment by vitaut** [comment]
Removed `FMT_USE_WINDOWS_H ` in https://github.com/fmtlib/fmt/commit/f733882b55779c68d2b1fbbe978f10c11113b6cd to prevent confusion. Thanks for bringing it to my attention.

**Comment by dalboris** [comment]
Thanks for the clarification and commit. It's a potentially useful feature which is now gone, but at least there's no confusion anymore. I'd suggest to bump the next version to 7.0 as to minimize surprise for the potential projects which would break (the error messages will be cryptic and with no obvious connection with {fmt}).
