### ISSUE TITLE
RFE: more information in format_error

### ISSUE THREAD

**Issue by avikivity** [fmtlib/fmt#1529]
If you get a format_error in a large code base, you have to way to find the offending code. If format_error were to capture the format string, that would give the developer something to grep on.

Compile-time format string validation is of course better, but I understand not quite production quality yet.

**Comment by vitaut** [comment]
Thanks for the suggestion. Unfortunately it would require rethrowing or a fair amount of bookkeeping neither of which is desirable. However there are other options:

* Intercept `format_error` throw in a debugger
* Redefine `FMT_THROW` and make it report the stack trace or its part - this will give more precise information than a format string
* Compile-time checks

The compile-time checks are successfully used in production. They have some limitations and require macros but there are no known issues. Compile-time checks are particularly useful in logging because there you often already have macros and `FMT_FORMAT` ugliness can be hidden from users.
