### ISSUE TITLE
fmt::format vs snprintf speed issues

### ISSUE THREAD

**Issue by rummanwaqar** [fmtlib/fmt#1615]
I am trying to use fmt for formatting strings. **I was comparing it with snprintf and fmt::format seems to be slower then snprintf by higher than a factor of 3.** From the benchmarks of fmt vs printf on the README I would expect this to not be the case. Is there anything I am doing incorrectly with the usage?

I ran the following lines for snprintf and fmt::format 1000000 times:

**snprintf** 
```
constexpr auto utc_string_length = std::strlen("hhmmss.sssssssss") + 1;
std::string utc_string(uint8_t hour, uint8_t minute, uint8_t seconds, uint32_t ns) {
  std::array<char, utc_string_length> buffer;
  ::snprintf(buffer.data(), buffer.size(), "%02d%02d%02d.%09lu", hour, minute, seconds, ns);
  return std::string(buffer.data());
}
````

**fmt::format**
```
std::string utc_fmt(uint8_t hour, uint8_t minute, uint8_t seconds, uint32_t ns) {
        constexpr auto compiled_format =
            fmt::compile<int, int, int, int>(FMT_STRING("{:02d}{:02d}{:02d}.{:09d}"));
        return fmt::format(compiled_format, hour, minute, seconds, ns);
}
```

Results:
snprintf took: 402.469ms
fmt took: 1473.22ms

**Comment by vitaut** [comment]
I ran a small benchmark based on your code snippets and got completely different results:

```
Running ./utc-benchmark
Run on (8 X 2800 MHz CPU s)
CPU Caches:
  L1 Data 32K (x4)
  L1 Instruction 32K (x4)
  L2 Unified 262K (x4)
  L3 Unified 8388K (x1)
Load Average: 1.78, 1.89, 2.44
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
snprintf       189766 ns       189205 ns         3734
format         141258 ns       140954 ns         5016
```

`fmt::format` was ~30% faster than `snprintf` with 1 iteration taking ~140ns. You might need to enable compiler optimizations since your numbers are ~10x bigger. Also note that format specifications in `snprintf` snippet are incorrect.

Here's the benchmark that I've used:
```c++
#include <benchmark/benchmark.h>
#include <array>
#include <cstdio>
#include <fmt/compile.h>
#include <random>
#include <vector>

struct Data {
  uint8_t hour;
  uint8_t minute;
  uint8_t seconds;
  uint32_t ns;
};

std::vector<Data> generate_random_data() {
  auto data = std::vector<Data>();
  auto gen = std::mt19937_64();
  for (auto i = 0; i < 1000; ++i) {
    auto d = fmt::internal::bit_cast<Data>(gen());
    data.push_back(d);
  }
  return data;
}

auto data = generate_random_data();

void snprintf(benchmark::State &state) {
  constexpr auto utc_string_length = 17;
  while (state.KeepRunning()) {
    for (auto d : data) {
      std::array<char, utc_string_length> buffer;
      ::snprintf(buffer.data(), buffer.size(),
                 "%02d%02d%02d.%09lu", d.hour, d.minute, d.seconds, d.ns);
      std::string result(buffer.data());
      benchmark::DoNotOptimize(result);
    }
  }
}

BENCHMARK(snprintf);

void format(benchmark::State &state) {
  while (state.KeepRunning()) {
    for (auto d : data) {
      constexpr auto compiled_format =
          fmt::compile<int, int, int, int>(FMT_STRING("{:02d}{:02d}{:02d}.{:09d}"));
      auto result = fmt::format(compiled_format, d.hour, d.minute, d.seconds, d.ns);
      benchmark::DoNotOptimize(result);
    }
  }
}

BENCHMARK(format);

BENCHMARK_MAIN();
```

**Comment by rummanwaqar** [comment]
Thanks

**Comment by iflyee** [comment]
@vitaut I am confused because I got the opposite result with your code.
2021-01-14T20:27:31+08:00
Running ./test_format3
Run on (1 X 2500.03 MHz CPU )
CPU Caches:
  L1 Data 32 KiB (x1)
  L1 Instruction 32 KiB (x1)
  L2 Unified 1024 KiB (x1)
  L3 Unified 33792 KiB (x1)
Load Average: 0.08, 0.14, 0.17
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
snprintf       302394 ns       297754 ns         2332
format        3264507 ns      2779709 ns          252

**Comment by iflyee** [comment]
@vitaut I am confused because I got the opposite result with your code.
2021-01-14T20:27:31+08:00
Running ./test_format3
Run on (1 X 2500.03 MHz CPU )
CPU Caches:
L1 Data 32 KiB (x1)
L1 Instruction 32 KiB (x1)
L2 Unified 1024 KiB (x1)
L3 Unified 33792 KiB (x1)
Load Average: 0.08, 0.14, 0.17
Benchmark Time CPU Iterations
snprintf 302394 ns 297754 ns 2332
format 3264507 ns 2779709 ns 252

**Comment by iflyee** [comment]
@vitaut I am confused because I got the opposite result with your code.
```021-01-14T20:27:31+08:00
Running ./test_format3
Run on (1 X 2500.03 MHz CPU )
CPU Caches:
  L1 Data 32 KiB (x1)
  L1 Instruction 32 KiB (x1)
  L2 Unified 1024 KiB (x1)
  L3 Unified 33792 KiB (x1)
Load Average: 0.08, 0.14, 0.17
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
snprintf       302394 ns       297754 ns         2332
format        3264507 ns      2779709 ns         252
```

**Comment by vitaut** [comment]
Looking at the numbers you are probably testing the debug version. Also note that

**Comment by iflyee** [comment]
Got it. Thanks.
