### ISSUE TITLE
wchar_t is UTF-32 at Linux and MacOS

### ISSUE THREAD

**Issue by sayurin** [fmtlib/fmt#1651]
wchar_t is UTF-16 at Windows, but UTF-32 at Linux and MacOS.
So converting utf8_to_utf16 generates invalid character code.
https://github.com/fmtlib/fmt/blob/6f435f55c88f6a143e064fa061ee32ae4152bca9/include/fmt/chrono.h#L776-L779

**Comment by vitaut** [comment]
You are right that `wchar_t` can be UTF-32. However it doesn't matter in this particular case because units only contain ASCII characters and `µ` which have the same values in UTF-16 and UTF-32. I clarified this in a comment: https://github.com/fmtlib/fmt/commit/4a617f25c60451e5767b2e095233b05f09ea8720

**Comment by sayurin** [comment]
@vitaut, if ASCII only, why convert to UTF-16 with utf8_to_utf16? It can be simple cast following std::copy.

**Comment by vitaut** [comment]
There is one non-ASCII character `µ` which needs to be converted.

**Comment by sayurin** [comment]
Thanks. So why conveting is applied for wchar_t only? char16_t and char32_t need same ceonvertion?

**Comment by vitaut** [comment]
No good reason, just nobody has implemented `char16_t`/`char32_t` support in chrono formatter yet.

**Comment by sayurin** [comment]
I see.
