### ISSUE TITLE
4.x branch fails to compile in VS2008 for CE6

### ISSUE THREAD

**Issue by escherstair** [fmtlib/fmt#1746]
I don't know if this is a supported scenario, but based on #1066 branch 4.x should support C++98 compiler.
And so I tried to compile it with VS2008; following [usage](https://fmt.dev/4.1.0/usage.html) I added `format.h` and `format.cc`.

I get an issue:
`format.h(374) : fatal error C1083: Cannot open include file: 'intrin.h': No such file or directory`

Is this a supported scenario?

**Comment by vitaut** [comment]
> Is this a supported scenario?

Yes in a sense that I'll be happy to accept a PR to fix this.

Basically the `#ifdef` in
https://github.com/fmtlib/fmt/blob/8ad1c12fb407f5619d59a97badcd737a3ccb2952/fmt/format.h#L373
should be updated to excluded VS2008 and earlier.

Could you submit a PR since you are in the best position to test the fix?

**Comment by escherstair** [comment]
I've just double checked and the problem is not so easy to fix, unfortunately.
`intrin.h` exists for VS2008, but only when the target is x86.
When the target is CE6, a lot of functions are missing from the SDK.
Moreover, I define `UNICODE` and `_UNICODE` to use the wide-char strings and a lot of errors come from that.
I don't know if 4.x branch has support for wide-char (and only CE6 is missing) or not.

And so a lot of work to be done so that CE6 with UNICODE is fully supported.
I'm going to see if I can do something.

**Comment by escherstair** [comment]
I added PR #1749 but I need review.
Thanks
