### ISSUE TITLE
not-user-friendly error reporting

### ISSUE THREAD

**Issue by W3LLD0NE** [fmtlib/fmt#1769]
"error C2338: Cannot format argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types"

this is very disappointing message because it does not write the types that should be reviewed. in my case, there was a long error-list that just went down to the first occurence of fmt::print() call in the file, which was absolutely unrelated to the issue because error was on another line with std::thread::id type.

can you make error reporting more verbose and user-friendly?

vs2019 16.6.3 btw.

**Comment by vitaut** [comment]
Improved the error message in https://github.com/fmtlib/fmt/commit/0097cf113d34ea265f25ea944f23406670be7e23. Now it contains the name of the unformattable type:

```c++
#include <fmt/core.h>

struct how_about_no {};

int main() {
  fmt::print("{}", how_about_no());
}
```

```
include/fmt/core.h:1264:3: error: static_assert failed due to requirement
'fmt::v7::detail::formattable<how_about_no>()' "Cannot format argument.
To make type T formattable provide a formatter<T>
      specialization: https://fmt.dev/latest/api.html#formatting-user-defined-types"
...

```

**Comment by W3LLD0NE** [comment]
thanks you for fast response!

**Comment by kjczarne** [comment]
Would it also be possible to add to the trace the line number where `fmt` encountered an unformattable entity? In my project I use an external `Formatter` class because we need several different textual representations. We have wrappers around primitives which I first unpack and then I use `fmt::format`. Each time I forget to unwrap, I have to check each and every invocation of `fmt::format` to see where I went wrong.
