### ISSUE TITLE
Compile-time format string checks by default

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#2022]
In C++20 we can have format string checks with the normal API, no macro or UDL is required (https://godbolt.org/z/qrh3ee):

```c++
#include <fmt/format.h>

template <typename... Args>
struct format_str {
  fmt::string_view str;

  template <size_t N>
  consteval format_str(const char (&s)[N]) : str(s) {
    using checker = fmt::detail::format_string_checker<
      char, fmt::detail::error_handler, Args...>;
    fmt::detail::parse_format_string<true>(
      fmt::string_view(s, N), checker(s, {}));
  }
};

template <class... Args>
std::string format(
    format_str<std::type_identity_t<Args>...> fmt,
    const Args&... args) {
  return fmt::format(fmt.str, args...);
}

int main() {
  auto s = format("{:d}", 42);
  fmt::print("{}\n", s);
}
```

**Comment by alexezeder** [comment]
One small concern here is that compile-time checks work only for format strings that don't have named identifiers since, currently, named arguments are not able to provide their names at compile-time.
I'm not so concern about the same behavior of compile-time checks invoked by `FMT_STRING`, because it's kinda extension, which just fails to work with named identifiers by failing a compilation process.
But it feels strange, at least for me, to disable compile-time checks (that will be enabled by default) only for format strings with named identifiers.

**Comment by vitaut** [comment]
Compile-time checks can potentially be made to work with a UDL form of named arguments.

**Comment by alexezeder** [comment]
> Compile-time checks can potentially be made to work with a UDL form of named arguments.

But that's only one way of creating named arguments. The problem with `fmt::arg(name, value)` would still be relevant.

**Comment by vitaut** [comment]
> The problem with fmt::arg(name, value) would still be relevant.

Right. Maybe some day we'll have parametric expressions or constexpr arguments that will make it possible.

**Comment by vitaut** [comment]
Compile-time checks are enabled now in compilers that have working `consteval` (gcc 10+, clang 11+).
