### ISSUE TITLE
Dedicated handling of std::filesystem::path objects with several new type specifiers

### ISSUE THREAD

**Issue by sebastianzander** [fmtlib/fmt#2082]
Please see and label the following as a feature request _and_ a question for how to implement it myself (see below).

I am looking for a way to comfortably output ``std::filesystem::path`` objects in different ways. For example like so:

```
// working directory: /home/projects/bin/
// actual file path: /home/projects/images/cat.png
std::filesystem::path imagePath("../images/cat.png");

// regarding std::filesystem::path::string()
fmt::print("Loading image from \"{}\"", imagePath);  // Loading image from "../images/cat.png"

// regarding std::filesystem::path::root_path()
fmt::print("Loading image from \"{:/}\"", imagePath);  // Loading image from "/home/projects/bin/../images/cat.png"

// regarding std::filesystem::path::relative_path()
fmt::print("Loading image from \"{:.}\"", imagePath);  // Loading image from "../images/cat.png"

// regarding std::filesystem::weakly_canonical(const std::filesystem::path&)
fmt::print("Loading image from \"{:c}\"", imagePath);  // Loading image from "/home/projects/images/cat.png"

// regarding std::filesystem::path::filename()
fmt::print("Loading image from \"{:f}\"", imagePath);  // Loading image from "cat.png"

// regarding std::filesystem::path::stem()
fmt::print("Loading image from \"{:s}\"", imagePath);  // Loading image from "cat"

// regarding std::filesystem::path::parent_path()
fmt::print("Loading from directory \"{:p}\"", imagePath);  // Loading from directory "/home/projects/images"
```

These are some type specifiers that I came up with. I am sure they would be _niche_ specifiers but effectively it saves the user either the extra `.string()` or the improper automatic string cast (with the added double quotes and escaped path separators) otherwise. The actual specifier chars are of course subject for debate.

I don't know if this functionality would be something that users may take notice of since they are probably used to accessing the respective ``std::string`` returning methods in ``std::filesystem::path``. But there are already some exotic and seldomly used type specifiers and if my proposed ones will get documented I am sure that people will use them.

If this doesn't seem like a useful addition to this library, could someone at least guide me towards the the source files where I could implement it under my own fork of fmtlib? I could then offer it/create a pull request anyway.

Kind regards, 
Sebastian Zander

**Comment by vitaut** [comment]
This can be implemented using the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types, you don't need to fork {fmt}. I don't think we should implement it in {fmt} itself in the proposed form because it would be inconsistent with [P1636 Formatters for library types](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1636r2.pdf). Path formatting is already supported via the iostreams interface but a `formatter` specialization consistent with P1636 would be welcome.

**Comment by sebastianzander** [comment]
Thank you for guiding me towards P1636 and the extension API. Maybe I'll find the time to create a P1636 consistent specialization.

**Comment by sebastianzander** [comment]
If someone is interested in how I solved it for my project, here is a source code snippet that should be self-contained:

```
#include <spdlog/fmt/bundled/format.h>

template <>
struct fmt::formatter<std::filesystem::path>
{
    char presentation = 's';

    constexpr auto parse(format_parse_context& ctx)
    {
        auto it = ctx.begin(), end = ctx.end();
        if(it != end &&  (*it == '/' || *it == '.' || *it == 'c' || *it == 'f' || 
            *it == 's' || *it == 'n' || *it == 'p' || *it == 'e')) presentation = *it++;

        if(it != end && *it != '}')
            throw format_error("invalid format");

        return it;
    }

    template <typename FormatContext>
    auto format(const std::filesystem::path& p, FormatContext& ctx)
    {
        switch(presentation) {
        case '/': return format_to(ctx.out(), "{}", p.root_path().string());
        case '.': return format_to(ctx.out(), "{}", p.has_root_path() ? p.relative_path().string() : p.string());
        case 's': return format_to(ctx.out(), "{}", p.string());
        case 'n': return format_to(ctx.out(), "{}", p.stem().string());
        case 'f': return format_to(ctx.out(), "{}", p.filename().string());
        case 'e': return format_to(ctx.out(), "{}", p.extension().string());
        case 'c': return format_to(ctx.out(), "{}", std::filesystem::weakly_canonical(p).string());
        default:  return format_to(ctx.out(), "{}", p.string());
        }
    }
};
```

I am not sure about the [P1636 Formatters for library types](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1636r2.pdf) though as I am not (yet) a OpenSource developer and thus not very familiar with such documents. @vitaut was your comment about the consistency regarding the default handling and when no type specifier is given like here:

```
std::filesystem::path imagePath("..\\images\\cat.png");
fmt::print("Loading image from \"{}\"", imagePath);
fmt::print("Loading image from \"{:s}\"", imagePath);
```

Such that the output is the same as it is without a formatter (i.e. includes double quotes and escaped path separators)? The output of the example above would be something like this:

```
Loading image from ""..\\images\\cat.png""
Loading image from "..\images\cat.png"
```

**Comment by vitaut** [comment]
> was your comment about the consistency regarding the default handling and when no type specifier 

It was mostly about other specifiers like `/` which are not supported by P1636.

**Comment by jmarrec** [comment]
> This can be implemented using the extension API: https://fmt.dev/latest/api.html#formatting-user-defined-types, you don't need to fork {fmt}. I don't think we should implement it in {fmt} itself in the proposed form because it would be inconsistent with [P1636 Formatters for library types](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1636r2.pdf). Path formatting is already supported via the iostreams interface but a `formatter` specialization consistent with P1636 would be welcome.

@vitaut I've wanted to be able to `fmt::print` a path directly. I've started looking on to add a formatter compliant with P1636 as you suggested directly in fmt. I found this issue, so I thought I'd discuss it here instead of opening another one (and I didn't open a PR because I am unsure which header to declare this in)

You can find a compiler explorer link with some alternatives here: https://godbolt.org/z/zeWEbox8v

Would you be kind enough to take a quick look please and let me know if this is going _roughly_ in the right direction?

----- 

Note: One issue I **thought** I saw right off the bat is that it seems you cannot forward declare `std::filesystem(::experimental)::path`... As you probably are well aware of, `std::filesystem` is a huge mess where some compiler versions find it in `experimental/filesystem` or `filesystem`, and may need a `-lstdfsc++` link flag to work. (My compiler explorer link has one GCC 7.5 that does need it as an example).

But it turns that if you are including the header, declaring the formatter, but not actually using `fs::path` anywhere in your code, then you do not need a link flag.

**Comment by vitaut** [comment]
> Would you be kind enough to take a quick look please and let me know if this is going roughly in the right direction?

Inheriting from `formatter<string_view>` is reasonable but I recommend not using ostreams in the implementation. All you need is to take `p.string<CharT,Traits>()`, quote it and pass the result to `formatter<string_view>::format`.
