### ISSUE TITLE
Seem like error in std::wstring VS2019

### ISSUE THREAD

**Issue by ouliuquan** [fmtlib/fmt#2104]
Test in many example, but faild in supported std::wstring

`#include <fmt/core.h>

int main() {
    std::wstring s = L"Hi";
    fmt::print(s);
}`

**Comment by OnurKader** [comment]
You need to include `format.h` to be able to print wstring's

[Godbolt](https://godbolt.org/z/f7q68b)

[Docs](https://fmt.dev/dev/api.html#format-api)

You should also print strings like `fmt::print("{}", s);` so `s` doesn't get treated as a format string.

**Comment by derossm** [comment]
The godbolt link is for gcc, not MSVC2019. Under MSVC2019 with /std:c++latest, fmt doesn't work at all because godbolt has v5 which seems to not be C++20 compatible. https://godbolt.org/z/8oK4on

That said, on my local machine, fmt::print v7 does work normally for wstring in MSVC2019 with /std:c++latest. However, if used with spdlog, wstring does break all of their usage of fmt by mixing chars with wchars somewhere in calls to fmt.

So, oddly enough, this bug seems to be appropriately closed here, but with dubious initial evidence. It did highlight fmt being about a year out of date on godbolt. And an adjacent bug in a popular library using fmt exists.

I don't know how to update libraries on godbolt, or I would offer to take care of that. I did check, and the most recent (and only) option available is definitely "vcpkg 2020.04" for fmt in the libraries menu of godbolt. Which is weird, because 7.1.3 is on vcpkg.

**Comment by OnurKader** [comment]
I didn't choose MSVC because you can't link, or just run?, the code on Godbolt.

But yeah C++17 works fine, I don't know why C++20 is having a problem with it, you could open an issue on spdlog.

Does using `#define SPDLOG_WCHAR_TO_UTF8_SUPPORT` help?
