### ISSUE TITLE
Historical background on formatter<>, arg_formatter, and friends

### ISSUE THREAD

**Issue by barcharcraz** [fmtlib/fmt#2126]
I've been reading through libfmt's `formatter<>`,  `arg_formatter`, `custom_arg_formatter`, and `default_arg_formatter implementations as we implement them in MSVC's STL for std::format and I think some historical context would be helpful to us. I have a few related questions.

From what I can tell it looks like libfmt started out with just `fmt::formatter<>` specializations, possibly delegating to arg_formatter as the actual visitor. It looks like custom_arg_formatter and default_arg_formatter were later added as throughput optimizations. Is this picture of the historical evolution of these types correct?

It looks to me like fmt::formatter<T, Char> (https://github.com/fmtlib/fmt/blob/58aa04573f6fab54dd998183d333bf9d630843ee/include/fmt/format.h#L3518) is actually completely unused except for when processing compile time format specs. Is this correct? I've looked at the source code pretty closely and at debug-info from some test programs and instantiations of this formatter do seem absent.

Are there any situations where an `arg_formatter` is used _without_ specs? There is code to support this but from reading through the flow of formatting I don't think it's ever used.

I'd like more historical information on the separation between `arg_formatter_(base)::operator()`s and `write(out, T, specs)` free functions. Which ones came first and has functionality moved from one to the other over time (I get the feeling things have moved from arg_formatter to free functions but I could be wrong)?

Do you have any further plans for arg_formatter / "backend flow" refactors?

Thanks for any clarity you can give.

**Comment by vitaut** [comment]
> Is this picture of the historical evolution of these types correct?

Partly. `custom_arg_formatter` was an experimental API that allowed custom formatting of built-in types such as `int` and it has been removed. `default_arg_formatter` is an optimization for the common case of the default (empty) format specifications. And `formatter` is an extension point for user-defined types.

> It looks to me like `fmt::formatter` is actually completely unused except for when processing compile time format specs. Is this correct?

Formatter specializations of built-in and string types are unused internally but can be used by user specializations.

> Are there any situations where an arg_formatter is used without specs?

I think it can be used with empty specs in "{:}" right now.

> I'd like more historical information on the separation between arg_formatter_(base)::operator()s and write(out, T, specs) free functions. Which ones came first and has functionality moved from one to the other over time (I get the feeling things have moved from arg_formatter to free functions but I could be wrong)?

`arg_formatter[_base]` were mainly used to support the `custom_arg_formatter` API and to some extent the `printf` implementation. Most of their functionality has been moved to the `write` functions. There isn't much reason for `arg_formatter[_base]` to exist any more other than compatibility with C++11 which doesn't have generic lambdas.

> Do you have any further plans for arg_formatter / "backend flow" refactors?

Moving the remaining functionality into free functions making `arg_formatter` and `arg_formatter_base` as small as possible and merging them (and in the future replacing with a lambda).

While I have your attention, please note that LEWG has approved [P2216](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p2216r2.html). Since it is a breaking change, you'll probably want to only ship `std::format` with this change applied once it is merged in the standard. It is currently under wording review.

**Comment by barcharcraz** [comment]
Thanks for the background. We've been following P2216 and I'll be at tomorrow's LWG call discussing it.
