### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by tanim87** [fmtlib/fmt#2140]
Dear Concern, 
While making the fmt, I am getting the following error:
Building CXX object test/CMakeFiles/format-test.dir/format-test.cc.o
/usr/local/src/fmt/test/format-test.cc:1487:20: error: call to 'ptr' is ambiguous

Would you please help me with it? 
I am using Ubuntu 16.04

Thanks.

**Comment by alexezeder** [comment]
Could you please provide compiler info?

**Comment by tanim87** [comment]
gcc 8.10

**Comment by alexezeder** [comment]
Looks like it should just work with the `master` branch of {fmt} on [Compiler Explorer](https://godbolt.org/z/8W1zne).
Do you have full output for this error, like function candidates, since the call is ambiguous?

**Comment by tanim87** [comment]
![Screenshot_2021-02-21_01-06-44](https://user-images.githubusercontent.com/42817244/108618158-5f619a80-73e1-11eb-8f9d-80c8b629982d.png)
I have attached the complete screenshot. I could not find log file that would give more insight. Let me know if this will work. Thanks.

**Comment by alexezeder** [comment]
Thanks, this definitely helped. For some reason, this specific version of GCC is able to decay function pointers to void pointers, just like MSVC, so this branch should be disabled for this GCC version too:
https://github.com/fmtlib/fmt/blob/7e72673d87cc44340f4b808d0b536e4e191342b5/include/fmt/format.h#L3837-L3844
You can check it locally just by commenting out the code above.

But since I don't know how to make it in a more versatile way, I think we should just wait for more experienced people for proper fix.

**Comment by vitaut** [comment]
I think we could SFINAE this overload away on function to `const void*` pointer convertibility.

**Comment by alexezeder** [comment]
Actually there is another problem with `fmt::ptr` and old Clang versions (<7.0) - https://godbolt.org/z/j57Kzx. Actually, this problem is even more interesting than I thought - https://godbolt.org/z/sEsTE7.

But as far as I can see, following workarounds are able to satisfy all compilers - https://godbolt.org/z/Y8sadG. I'll create a PR with this code soon.

**Comment by tanim87** [comment]
Your suggestion worked! Thanks.
