### ISSUE TITLE
Formatting floats with at most N digits after dot

### ISSUE THREAD

**Issue by ngrodzitski** [fmtlib/fmt#2155]
I want to render double values with at most N digits after `.`

```C++
#include <fmt/format.h>
#include <fmt/printf.h>

int main()
{
    double x = 12345;
    double y = 1234.5;
    double z = 123.45;
    double q = 12.345;
    double w = 1.2345;
    auto f = "{:.2f}\n";
    fmt::print(f, x);
    fmt::print(f, y);
    fmt::print(f, z);
    fmt::print(f, q);
    fmt::print(f, w);
}
```

this gives me the following output:
```
12345.00
1234.50
123.45
12.35
1.23
```

But I want to have the following output:
```
12345 (12345.0 is also ok)
1234.5
123.45
12.35
1.23
```
What should be a format string.
I'm trying to figure out proper formatting options, but nothing works.
A quick example is here: https://godbolt.org/z/vE75Wo

**Comment by vitaut** [comment]
I don't think you can express it in a format string directly but you can use the `f` specifier and then remove trailing zeros and the decimal point.

**Comment by ceztko** [comment]
I was looking just for the same thing and it seems a very reasonable requirement. Why a new string syntax couldn't be added just to achieve what the OP is asking?

**Comment by vitaut** [comment]
The format string syntax is pretty much fixed at this point for compatibility with `std::format`. That said you can implement this functionality via the extension API without changes to the core library.

**Comment by ceztko** [comment]
I see. It's a pity that this got missed during the format facilities rejuvenation process. Modern formatters supports this semantics, eg. .NET[1], Java[2], javascript[3].

[1] https://dotnetfiddle.net/eie9dO
[2] https://stackoverflow.com/a/4184015/213871
[3] https://stackoverflow.com/a/55448529/213871

**Comment by ceztko** [comment]
Using .NET (where I'm more comfortable), the OP seems to ask the following:

```
using System;
using System.Globalization;
					
public class Program
{
	public static void Main()
	{
		double x = 12345;
		double y = 1234.5;
		double z = 123.45;
		double q = 12.345;
		double w = 1.2345;	
		Console.WriteLine(String.Format("{0:0.##}", x, CultureInfo.InvariantCulture));   // Prints 12345
		Console.WriteLine(String.Format("{0:0.##}", y, CultureInfo.InvariantCulture));   // Prints 1234.5
		Console.WriteLine(String.Format("{0:0.##}", z, CultureInfo.InvariantCulture));   // Prints 123.45
		Console.WriteLine(String.Format("{0:0.##}", q, CultureInfo.InvariantCulture));   // Prints 12.35
		Console.WriteLine(String.Format("{0:0.##}", w, CultureInfo.InvariantCulture));   // Prints 1.23
	}
}
```

This seems to agree with what the OP would accept, quoting the question:

```
But I want to have the following output:
12345 (12345.0 is also ok)
1234.5
123.45
12.35
1.23
```

> and is supported

@vitaut that would be great! What's the syntax? I'm also struggling to find it.

**Comment by vitaut** [comment]
I'm not familiar with C# but Java and JavaScript examples look like the usual fixed format. As I wrote before trailing zeros and decimal point can be removed as a trivial postprocessing step, possibly wrapped in an extension API for better usability. The C# syntax looks extremely overengineered.

**Comment by ceztko** [comment]
I'm sorry for replying late, and still in this closed topic. It seems this lack of feature is still hitting me composing a more complex string. In particular I'd like to add a custom formatter that can be used in another pattern formatted string. I honestly would like to re-open the issue or to create a new one to ask for official support in `fmt`. Anyway you said:

> possibly wrapped in an extension API for better usability

I understand the core library can be extended with the `formatter` template API which looks to be forward only, meaning that I can't re-use the actual float formatter. This is what I was trying:

```
template <>
struct fmt::formatter<custom_double> : fmt::formatter<double>
{
    auto format(custom_double c, format_context& ctx)
    {
        auto ret = formatter<double>::format(c.value, ctx);
        // I would lie to remove the trailing zeroes here...but the appender is write/forward only
        return ret;
    }
};
```

So, what do you suggest here? Maybe can you point me to the actual function performed in `fmt`? I would like to not reinvent the wheel and avoid obvious mistakes/bugs.

> I'm not familiar with C#

(Better say .NET here) It's strange you say so since there are analogies between fmt and .NET. syntax. They may have same roots.

> The [.NET] syntax looks extremely overengineered

Why you think so? In `0:0.##`, the `0:` part is just the argument index, and `0.##` . Maybe you meant verbose, because potentially the pattern could be as long as the desired precision (eg. `0.################`). Verbose (potentially) yes, overengineered no. In general, I think this feature would have been very desiderabile also for standardization and it's a pity it was forgotten.

**Comment by vitaut** [comment]
> So, what do you suggest here? Maybe can you point me to the actual function performed in fmt?

The usual approach is to format into a temporary buffer and then massage the result. I guess you could look at the standard formatter: https://github.com/fmtlib/fmt/blob/f6f920a1a877271ab36114bf4b6b107bc02c73e3/include/fmt/core.h#L3002 (e.g. the double case).
