### ISSUE TITLE
Doc: Unclear contract for retention of `fmt::arg` results

### ISSUE THREAD

**Issue by BillyDonahue** [fmtlib/fmt#2178]
Docs for `fmt::arg()` seem to indicate that the returned object my depend on temporaries created in the function call expression, and that it would be unsafe to use the returned object after the full expression expires.

https://github.com/fmtlib/fmt/blob/b8ff3c182004571dd9e1452239f1da6fde8f23e0/include/fmt/core.h#L1622-L1623

That's no longer true as other examples like https://github.com/fmtlib/fmt/blob/b8ff3c182004571dd9e1452239f1da6fde8f23e0/include/fmt/args.h#L180-L181 show the result being retained in `auto` variables and passed to `fmt::dynamic_format_arg_store` via `push_back`.

I want to use `dynamic_format_arg_store` but it looks like I'm breaking the `fmt::arg` contract to do it.
I know it's safe, but the docs don't quite match the reality.

Should the "It should only be used in a call to a formatting function" be removed or updated?

**Comment by vitaut** [comment]
Good catch, thanks!

The example in `fmt/args.h` is pretty bad, we shouldn't be storing the return value of `fmt::args`. I've updated the comments in https://github.com/fmtlib/fmt/commit/5a1127b726879e21e5a9613fc620d08413d39054 and disabled wrapping named arguments in `cref` since it's misleading (argument name is always stored by reference) and doesn't work with rvalue references.

**Comment by BillyDonahue** [comment]
A new comment says "The name is always stored by reference", but it is actually copied into the `dynamic_args_` as a `std::basic_string<char_type>`.
https://github.com/fmtlib/fmt/blob/6151d0dc1e7c0deb40a3a5d9e1ac3f506830555c/include/fmt/args.h#L190-L205

Maybe it's hard to see because `arg_name` looks like `arg.name`.

**Comment by vitaut** [comment]
You are right. Fixed in https://github.com/fmtlib/fmt/commit/8308f52c2aaddbe08f9ed20e4ce9f46f6bc29e3f.
