### ISSUE TITLE
Request: add a default formatter for std::chrono::zoned_time

### ISSUE THREAD

**Issue by LamboPita** [fmtlib/fmt#2511]
Hello, it would be lovely to have a default format for zoned_time objects to easily print them. The following snippet:
```
std::chrono::zoned_time zt{ std::chrono::current_zone(), std::chrono::system_clock::now() };
fmt::print("{}", zt);
```

could result in:

`2021-09-24 22:44:20.1914414 EDT`

**Comment by vitaut** [comment]
Sounds reasonable, a PR is welcome!

**Comment by Lounarok** [comment]
Does any compiler support `std::chrono::zoned_time` at the moment?
[msvc 19.latest](https://godbolt.org/z/n38asd9Ef)
[gcc trunk](https://godbolt.org/z/6Mv44WqbY)
[clang trunk](https://godbolt.org/z/Tbs4Pr8je)

All of them failed to compiled this test 
```
#include <chrono>
#include <iostream>
int main() {
  std::cout<< std::chrono::zoned_time{} << std::end;
}
```

**Comment by alexezeder** [comment]
Looks like MSVC supports `std::chrono::zoned_time`, according to the [C++20 library features table](https://en.cppreference.com/w/cpp/compiler_support#:~:text=Calendar%20and%20timezone).

Also, you provide incorrect compiler options for MSVC and Clang, it should be:
* `/std:c++20` for MSVC. But ostream operator is not provided for some reason 🤷 - https://godbolt.org/z/oKqxKEbzd.
* `-std=c++20 -stdlib=libc++`, the second option switches standard library that Clang uses from GNU libstdc++ to LLVM libc++. But  `std::chrono::zoned_time` is not provided by libc++ currently - https://godbolt.org/z/h6n74f5rW.

More information about _Extending \<chrono> to Calendars and Time Zones_ support can be found on corresponding sites:
* [GCC](https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#:~:text=Extending%20chrono%20to%20Calendars%20and%20Time%20Zones)
* [Clang](https://libcxx.llvm.org/Status/Cxx20.html#:~:text=Extending%20chrono%20to%20Calendars%20and%20Time%20Zones)

**Comment by vitaut** [comment]
Closing as there are no plans to add a formatter for `zoned_time` but a PR would still be welcome.

**Comment by alllel** [comment]
Currently gcc-14 has full support for `zoned_time` with formatting both in `iostream` and in `std::format`:
```
#include <iostream>
#include <chrono>
#include <format>
 
int main(){
    auto t=std::chrono::system_clock::now();
    auto z=std::chrono::current_zone();
    std::chrono::zoned_time zt{z,t};
    std::cout<<zt<<std::endl;
    std::cout<<std::format("{:%F %T %Z}",zt)<<std::endl;
    return 0;
}
```

So maybe `fmt` somehow can use or import the existing `std::formatter`?

**Comment by cschreib-ibex** [comment]
Ah; I came here to say the same. I was debugging an issue in Howard Hinnant's `date` library (https://github.com/HowardHinnant/date/issues/921) related to printing localized zoned time points. When I tried to use `fmt` to get a comparison point, I realized it does not seem to support zoned time points at all. Yet `std::format` [does](https://en.cppreference.com/cpp/chrono/zoned_time/formatter) (since C++20 officially).

Howard Hinnant's `date` implementation of zoned time formatting can be used as an example of how to achieve this. At first glance it doesn't seem too bad, since it mostly boils down to formatting a `std::tm` with a specific time zone / GMT offset. I see `fmt` already has all the stuff needed to format a `std::tm` properly, including localised output.

The main difficulty (as I found out in the issue linked above) is that standard `std::tm` doesn't include time zone information; it does for some platforms, but that is non-standard. For other platforms, any format flag that intends to display the time zone (or offset) must be handled manually. That's straightforward since the information is contained in the time point, there aren't many format flags that explicitly output time zone/offset (`%Z` and `%z`), and the desired output is pretty easy to get. 

Where it gets more complicated is when requesting localized output. In particular, something like `{:L%c}` (which prints a full date+time in the locale's date-time format). The locale's definition of `%c` can sometime include the time zone (it is the case on Ubuntu `en_GB.UTF-8` and `en_US.UTF-8`, for example). Yet we can't pass the time zone information to the facet used for writing the localised string, because standard `std::tm` doesn't have it. And we can't hand-write the formatter for this, since there's no standard way to query the locale for what `%c` is supposed to display. The `date` library has the same issue (the one I linked to at the top). My conclusions were that, to the best of my understanding, there is no way to reliably implement this portably at the moment (without relying on `std::format`). But we can get very close, perhaps to the point where the non-portable aspect is academic and not a concern in practice.

Just thought I'd share this here, since it took me a fair bit of time to unearth all of this for `date`. I'd still recommend implementing this here, if only for parity with `std::format`.
