### ISSUE TITLE
Undefined behaviour when copying dynamic_format_arg_store

### ISSUE THREAD

**Issue by lucpelletier** [fmtlib/fmt#2653]
The copy constructor of dynamic_format_arg_store completely ignores the dynamic_args_ private member variable. This can unexpectedly cause undefined behaviour when a dynamic_format_arg_store instance is copied, since anything stored in dynamic_args_ will not get copied over. See the following for an example:

https://godbolt.org/z/8n7rnM55E

I can think of a couple of ways of fixing this problem, and I'd be happy to provide a PR with a fix, but I first wanted to get input from library maintainers on what would be the best solution.

**Comment by vitaut** [comment]
The easiest solution is to mark the copy ctor as deleted. A PR would be welcome.

**Comment by vitaut** [comment]
I think we should disable the copy ctor because it's currently broken. If someone has a use case they can contribute a fix later.

**Comment by vitaut** [comment]
Disable the broken copy ctor in https://github.com/fmtlib/fmt/commit/be51ee1ceb0553411cae166335b59e7ae5126527. I don't think there is much reason to copy `dynamic_format_arg_store` at all, it's better to copy the actual arguments and construct the argument list only before a formatting function call.

**Comment by vitaut** [comment]
Thanks for reporting.

**Comment by spyridon97** [comment]
@vitaut The actual arguments cannot be copied from an `dynamic_format_arg_store` (there is no public fuction for such functionality) so i believe the copy constructor is the way to go.

I did not copy the `dynamic_args_` inside `dynamic_format_arg_store` because `dynamic_arg_list` also does not have a copy constructor. I can add one but it's not gonna be constexpr. Are you fine with that?

**Comment by spyridon97** [comment]
@vitaut Any suggested solution?
