### ISSUE TITLE
is_utf8() has possible ODR violation

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#3002]
The C++ proposal "Formatted output" and this library are excellent, but I was always suspicious of the dispatch mechanism that (on Windows) chooses whether we call the Unicode or non-Unicode version. It is described in [Chapter 11 "Unicode" of the proposal](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2093r12.html#unicode). I think I found the problem.

The ODR can happen in the following scenario:

1. I use MSVC
2. I build one translation unit without [/utf-8 ](https://docs.microsoft.com/en-us/cpp/build/reference/utf-8-set-source-and-executable-character-sets-to-utf-8?view=msvc-170)
3. I build a different translation unit with the flag.
4. I link them together.

This scenario is very unlikely, but what is more likely is the following:

1. I use MSVC
2. I build library A without `/utf-8` and library A uses Fmt.
3. I build exe B with `/utf-8` which uses both library A and Fmt.
4. I link the exe to the libraries.

The violation of ODR happens because the string literal inside `is_utf8()` can be different.

**Comment by vitaut** [comment]
The committee has discussed it in the context of obtaining literal encodings that vary across TUs and there was no major concern. From the standard perspective such variation is not a thing and from the practical perspective it's benign because the functions that do the dispatch are inlined. That said compiling your code with potentially incompatible options is not recommended.
