### ISSUE TITLE
_isatty vs GetConsoleMode?

### ISSUE THREAD

**Issue by dimztimz** [fmtlib/fmt#3003]
In the paper there is this [note](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p2093r12.html#hist):

> Changes since R3:
> Replaced `_isatty(_fileno(stream))` with `GetConsoleMode(_get_osfhandle(_fileno(stream)), ...)` in a note in [format.functions] because the former may return 1 for streams not referring to a terminal.

What is the difference? Which one is more correct? Currently `_isatty()` is still used:

https://github.com/fmtlib/fmt/blob/81f1cc74a776581cdef8659d176049d3aeb743c6/include/fmt/format-inl.h#L1482-L1498

Related issue #2080. Is the fact that we return false when `WriteConsoleW()` fails good enough solution and there is no need for `GetConsoleMode`?

**Comment by vitaut** [comment]
For the purposes of the paper `GetConsoleMode` is the right thing because `_isatty` may return true when there is no console in some cases (I don't remember exactly which though). Implementation-wise it shouldn't matter because in the worst case there is extra transcoding in those cases which is then discarded but that should be uncommon.

**Comment by adah1972** [comment]
Ha, I have actually found this issue when redirecting console output to `nul` in benchmarking. `_isatty` says the `nul` file is a TTY....

I think a change to use `GetConsoleMode` might be good, if it does not incur significantly bigger overhead. The [LWG issue](https://cplusplus.github.io/LWG/issue4044) and the current C++ standard say `GetConsoleMode(_get_osfhandle(_fileno(stream)), ...)` should be used.
