### ISSUE TITLE
Acceptable format strings

### ISSUE THREAD

**Issue by matt77hias** [fmtlib/fmt#3052]
Any design reason why some of the below conversions do not work?

```c++
#include <fmt/core.h>
#include <fmt/xchar.h>

using FormatString     = fmt::basic_format_string< char,    int >;
using FormatWideString = fmt::basic_format_string< wchar_t, int >;

auto main() -> int
{
    [[maybe_unused]] auto f1 = fmt::format(FormatString    {  "{}" }, 1);
    [[maybe_unused]] auto f2 = fmt::format(FormatWideString{ L"{}" }, 1);// ERROR

    [[maybe_unused]] auto f3 = fmt::format( "{}", 1);
    [[maybe_unused]] auto f4 = fmt::format(L"{}", 1);

    [[maybe_unused]] auto f5 = fmt::format(fmt::basic_string_view< char >{    FormatString    {  "{}" } }, 1);// ERROR
    [[maybe_unused]] auto f6 = fmt::format(fmt::basic_string_view< wchar_t >{ FormatWideString{ L"{}" } }, 1);

    return 0;
}
```
https://godbolt.org/z/PYbcbWbaf

**Comment by vitaut** [comment]
The last two should not work because conversion from a format string to a string view is not constexpr. Compile-time checks are not fully implemented for `wchar_t` which is why the last one doesn't give an error. Technically they could be made to work but it would introduce duplicate checks which is undesirable.

This on the other hand shouldn't give an error:

```
    [[maybe_unused]] auto f2 = fmt::format(FormatWideString{ L"{}" }, 1);// ERROR
```
Again this is because of compile-time checks not fully implemented for `wchar_t`.

Incorrect error/non-error cases should be fixed in https://github.com/fmtlib/fmt/commit/e724bbea162839133b26a44313673bf14751fe3b. Thanks for reporting.

**Comment by matt77hias** [comment]
Works for gcc. MSVC seems to have a bug: https://godbolt.org/z/dv7bz7hb8
