### ISSUE TITLE
Logging example not working for fmt 9.1.0

### ISSUE THREAD

**Issue by albachten** [fmtlib/fmt#3156]
The logging example in the "Argument Lists" section of
https://fmt.dev/latest/api.html has a godbolt link https://godbolt.org/z/oba4Mc
that doesn't match the provided code and instead is the code for previous versions of fmt.

More importantly, the suggested code does not catch errors at compile time.
This is stopping me from using fmt 9.1.0.

Here is an example that should have a compile time error but instead has a runtime error:
https://godbolt.org/z/64KfxM3jj

**Comment by mwinterb** [comment]
The documentation has already been updated in current: https://fmt.dev/dev/api.html#argument-lists

It doesn't use `FMT_STRING` anymore since it's no longer necessary if you're compiling with `consteval` support from C++20, but you can re-add the `FMT_STRING` and it will catch invalid format strings in C++14 and later.

https://godbolt.org/z/KdcY5Pafh

**Comment by vitaut** [comment]
The latest docs also clarify the compile-time check API: https://fmt.dev/dev/api.html#compile-time-format-string-checks
