### ISSUE TITLE
How to print and still replace variables in a string literal?

### ISSUE THREAD

**Issue by infn-ke** [fmtlib/fmt#3187]
Is it possible to print and replace variables in a string literal? The google protobuf printer can do this and I find that very useful. E.g something like this...

```cpp
const char *s = R"(
name = `NAME`
age = `AGE`
)";

std::map<std::string, std::string> vars;
vars["NAME"] = "foo";
vars["AGE"] = "42";
fmt::print(vars, s);
```

**Comment by mwinterb** [comment]
Seems like you want something like this:
https://github.com/fmtlib/fmt/blob/7df30f91aee5444a733cec0b911d21cebdeb62ae/test/args-test.cc#L95-L102
https://fmt.dev/latest/api.html#named-arguments has an example combining a named argument with a custom format specifier.

You'll need to use `vprint` instead of `print`: https://gcc.godbolt.org/z/bKx66c1ch

For your exact case, this seems to work, but I've never used named arguments so I don't know if this is guaranteed to: https://gcc.godbolt.org/z/5vze65x6c

**Comment by infn-ke** [comment]
@mwinterb thank you very much for the excellent answer! Much appreciated, and great feature!
