### ISSUE TITLE
Missing definition of FMT_BUILTIN_CLZ on Clang-CL

### ISSUE THREAD

**Issue by Epixu** [fmtlib/fmt#3213]
When building on latest (Clang 15.0.1 with MSVC-like command-line) Clang-CL I encounter this error:
```
format.h(3152,40): error : use of undeclared identifier 'FMT_BUILTIN_CLZ'
    if (leading_xdigit > 1) f.e -= (32 - FMT_BUILTIN_CLZ(leading_xdigit) - 1);
```
Introduced in [this commit](https://github.com/fmtlib/fmt/commit/91c024ed3322793cf0fddd81fc1a83c22eb61709) (i think, either way, its recent)
No other compiler seems to complain

**Comment by dodheim** [comment]
The commit that introduced the issue was 31364732dcf0b2697259b8dce3ac6c16c6d2daf8. The original problem from #519 doesn't affect modern Clang on Windows; in fact it probably never affected real Clang/LLVM, only Microsoft's short-lived Clang/C2 experiment, but that's just a guess.

My local workaround is just commenting the `FMT_MSC_VERSION` check in format.h:143. It needs to be a Clang/C2 check instead, but that experiment is _long_ dead, so maybe this workaround should just go away altogether...
