### ISSUE TITLE
Expose or extract useful utilities?

### ISSUE THREAD

**Issue by netheril96** [fmtlib/fmt#323]
This library contains more than the awesome formatting capabilities. It also has UTF8 to UTF16 conversion, cross platform `strerror_r`, detection of compiler features, etc. Can you expose them as public functions? Or extract them into a separate library?

**Comment by vitaut** [comment]
Thanks for the feedback.

System error API is already public: http://fmtlib.net/latest/api.html#system-errors. I don't think it's a good idea to expose `strerror_r`-like API because it requires awkward buffer management. Does the system error API work for you or are you looking for something else?

I'll be happy make UTF-8/UTF-16 converters public, but note that they are only implemented for Windows, because other platforms support UTF-8 natively. The converters need to be documented first though.

**Comment by netheril96** [comment]
I have my own exception hierarchy so I don't want to construct a `fmt::SystemError`. `strerror_r` is indeed awkward, so an better API would be just `std::string fmt::system_errmsg(int)`. Or with some better name.

**Comment by vitaut** [comment]
`format_system_error` is in the public API as of https://github.com/fmtlib/fmt/commit/9c780983465e44422ec9f61c52dc4d649a4870c1.

**Comment by netheril96** [comment]
Thanks!
