### ISSUE TITLE
How to set locale for output with MinGW

### ISSUE THREAD

**Issue by Fisteshak** [fmtlib/fmt#3270]
Documentation says, that fmt::print is locale-independent, as i understand it's just needed to set this locale using `std::locale::global`, for example `std::locale::global(std::locale("ru_RU.UTF-8"));` The problem is, i am using MinGW with GCC 11.3.0, which supports only "C" and "POSIX" locales, and `std::setlocale("Russian")` doesn't seem to work with `fmt::print` (however it works fine with `cout`). 

I am transferring data through network, including computer name. Without locale set, if name has russian symbols, `fmt::print` fails with `invalid utf8` exception. Is there any way to output is correctly?

I am newbie in C++, so i'm probably missing something, but i haven't found any solution.

**Comment by vitaut** [comment]
You don't need to set locale to print Cyrillic text. The "invalid utf8" error likely indicates that you are trying to print data encoded in the current code page rather than UTF-8. This only happens when printing to console and shouldn't affect formatting and sending data through network. I recommend changing the code page to UTF-8 or using UTF-16 Windows APIs to get the computer name and convert it to UTF-8.
