### ISSUE TITLE
The format_error thrown doesn't tell me much

### ISSUE THREAD

**Issue by joto** [fmtlib/fmt#3309]
When a formatting string can not find its argument (for instance when using `fmt:arg` and you forgot to set the argument), all I get is an `format_error` exception with the message `"argument not found"`. This makes it difficult to figure out what's missing. Can we have the name of the missing argument in the error message?

**Comment by vitaut** [comment]
Thanks for the suggestion but I don't think it's work investing into trying to report this considering that it won't help much in the common case where arguments are numeric (and even in the named case since it doesn't say which format call it applies to) and can be tricky with compile-time error reporting. That said you can validate named arguments at compile time using the UDL-based API: https://godbolt.org/z/vecv1853n or look at the stack trace to get to the problematic call.
