### ISSUE TITLE
Desired feature:  ability to disable sign printing on floating point zeros. (custom formatting)

### ISSUE THREAD

**Issue by spacemoose** [fmtlib/fmt#331]
We recently experimented with using fmtlib to alleviate a performance problem we were having with boost::format.  I'm quite impressed with the library, but I have a feature need that prevents me from using it as is.

We need the ability to NOT print a sign when a floating point representation is textually zero.  For example you have a number which is zero, but because of floating point precision issues, it's represented in memory is -0.000001.   When we print "0.00" we get an unwanted sign -- "-0.00".  We were able to solve this for boost::format by creating a custom num_put facet, but that approach won't work for fmtlib.

We can patch the library to get it to behave the way we want, but I suppose the reasons why this is undesirable is obvious.

So -- would you be interested in a patch that adds this functionality?  Obviously we would first have to discuss the interface for controlling such a feature.  I have some thoughts regarding the ability to add custom formatters to fmtlib similar to std::locale's facet functionality,  but perhaps you already have thoughts on this topic   If you think this might be interesting, let's start a dialogue.

**Comment by vitaut** [comment]
Thanks for the suggestion and your interest in the library.

You can achieve the desired behavior by providing a [custom argument formatter](http://fmtlib.net/latest/api.html), for example:

```c++
#include "fmt/format.h"

// A custom argument formatter that doesn't print `-` for floating-point values
// rounded to 0.
class CustomArgFormatter :
  public fmt::BasicArgFormatter<CustomArgFormatter, char>  {
  public:
  CustomArgFormatter(fmt::BasicFormatter<char, CustomArgFormatter> &f,
                     fmt::FormatSpec &s, const char *fmt)
    : fmt::BasicArgFormatter<CustomArgFormatter, char>(f, s, fmt) {}

  void visit_double(double value) {
    if (round(value * pow(10, spec().precision())) == 0)
      value = 0;
    fmt::BasicArgFormatter<CustomArgFormatter, char>::visit_double(value);
  }
};

std::string custom_format(const char *format_str, fmt::ArgList args) {
  fmt::MemoryWriter writer;
  // Pass custom argument formatter as a template arg to BasicFormatter.
  fmt::BasicFormatter<char, CustomArgFormatter> formatter(args, writer);
  formatter.format(format_str);
  return writer.str();
}
FMT_VARIADIC(std::string, custom_format, const char *)

int main() {
  custom_format("{:.2f}", -0.000001); // returns "0.00"
}
```

Will it work for you?

**Comment by vitaut** [comment]
I'm closing the issue but feel free to ask if you have any questions about this.

**Comment by spacemoose** [comment]
Just tried a quick test -- this looks like exactly what I need.  Thanks very much for your support, and the excellent library!

**Comment by spacemoose** [comment]
How can I accomplish the same thing using the fmt::printf interface?

**Comment by vitaut** [comment]
You can't do it right now with `fmt::printf` because `PrintfFormatter`, doesn't support argument formatters, but it's possible to extend it in the same way as `BasicFormatter`. Feel free to open an issue if you are interested in this functionality.

**Comment by danra** [comment]
FWIW, here's one more upvote to adding this: For a dB parameter with a minimum value of -24 and a 0.01 grid, a default value of zero for the parameter is calculated as `-24.0f + 0.01f × 2400.0f` which (in some build settings at least, due to fused-multiply-add) gives `-5.36e-7` on macOS vs. exactly zero on MSVC. Formatting the former to show a default value as `-0.0dB` in a user-facing display on one platform is not very elegant (arguably the bigger problem is that -5.36e-7 *isn't* exactly zero, which is the more important aspect in audio-related calculations; but usually that's negligible).

Back to my point, I wanted to use `std::format` or `fmtlib` format practically-zero as zero with no minus sign, but I saw they don't support that. I reluctantly resorted to roll my own patch (or rather, Claude did) to remove the minus post-formatting.

Writing this to provide some evidence this is actually useful, following the lack of evidence that's presented in [P2021R0](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2021r0.html).
