### ISSUE TITLE
string.h collides with standard C string.h

### ISSUE THREAD

**Issue by iSLC** [fmtlib/fmt#332]
I'm including ``format.cc`` directly into my project which requires ``format.h`` to be available in the include paths. But ``string.h`` is also in the same folder as ``format.h`` and that confuses the compiler when trying to include the standard ``<cstring>`` which in turn includes the C ``string.h``. Resulting in ``<cstring>`` actually including the ``string.h`` that comes with the **{fmt}** library. Which causes every occurrence of any function from ``<cstring>`` to generate an ``error: '::func' has not been declared``.

I would suggest to either use ``#include "fmt/format.h"`` inside ``format.cc`` so that I won't have to have the ``fmt`` folder in my include paths or rename the ``string.h`` header to something else.

For example, I renamed ``string.h`` to ``stringf.h`` and it compiles just fine.

Same goes with ``time.h``

_Compiler: MinGW GCC 5.3.0
IDE: Code::Blocks_

**Comment by vitaut** [comment]
Thanks for the bug report. You should add `fmt`'s parent directory rather than `fmt` itself to include directories, for example when building in the project directory:

```c++
> g++ -I. test.cc
```

`#include "string.h"` in `format.cc` is relative to the latter, so it should work without prefix, but please let me know if it is not the case with your compiler.

**Comment by vitaut** [comment]
That said it might be a good idea to add include prefix anyway to prevent confusion.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/e160c2b79a405757c1a6dab7e5a41b81c9e5ed05. Thanks again for reporting!
