### ISSUE TITLE
Including "fmt/chrono.h" causes custom formatters to fail with gcc 13.1.1 in c++20

### ISSUE THREAD

**Issue by theartful** [fmtlib/fmt#3419]
The title explains it all.
Here is a snippet
```C++
#include <fmt/chrono.h>
#include <fmt/core.h>

struct Struct {};

namespace fmt
{
template <>
struct formatter<Struct> {
    template <typename ParseContext>
    constexpr auto parse(ParseContext& ctx) const
    {
        return ctx.begin();
    }

    template <typename FormatContext>
    constexpr auto format(const Struct&,
                          FormatContext& ctx) const
    {
        return format_to(ctx.out(), "");
    }
};
}

int main()
{
    fmt::print("{}\n", Struct{});
}
```
And here is a reproducible compiler explorer link:
https://godbolt.org/z/GKzGoaKqP

This locally also fails using clang++ 15.0.7.
For some reason in my project, when I didn't include chrono.h it compiled successfully, but the godbolt link fails either way.

**Comment by brevzin** [comment]
This:
```cpp
return format_to(ctx.out(), "");
```
Now finds both `fmt::format_to` (as always) and `std::format_to` (because of `<chrono>` and because `fmt::appender` inherits from `std::back_insert_iterator`). 

In this particular case, it's possible for `{fmt}` to define `fmt::appender` in such a way that `std` isn't an associated namespace, that'd solve this particular problem, but if you passed some other argument into `format_to` that had `std` as an associated namespace, then you'd have the same problem and `{fmt}` couldn't help you.

Your best bet is to just qualify your `format_to` calls.

**Comment by theartful** [comment]
@brevzin
Yeah, that's the solution that I did eventually. I qualified it by `::fmt::format_to` and it worked locally. Godbolt isn't happy by this solution still however, so I think there still might be something wrong that requires fixing.
https://godbolt.org/z/rMKEdE5rf

**Comment by brevzin** [comment]
@theartful That's because `"Struct {}"` isn't a valid format string with no arguments, you need to escape the braces.

**Comment by vitaut** [comment]
As Barry already pointed out the fix is:

```c++
        return fmt::format_to(ctx.out(), "Struct{{}}");
```

**Comment by theartful** [comment]
yup sorry that was dumb of me
