### ISSUE TITLE
Feature Request: BasicWriter that writes to stdout

### ISSUE THREAD

**Issue by marton78** [fmtlib/fmt#352]
Hi,

it would be great if `fmt` could fill this omission, it could then be used as a replacement of `iostream`s.

**Comment by vitaut** [comment]
Thanks for the suggestion. The formatting functions such as `fmt::print` already support output to `stdout`, but I agree that it would be nice to have similar functionality in the write API. The main issue that has to be solved is buffer management. Since `fmt::BasicWriter` already uses the output buffer, the `FILE`'s one is probably redundant and file descriptors should be used instead.

**Comment by vitaut** [comment]
Since `BasicWriter` is mainly an optimization, it will likely be superseded by the format API with compile-time handling of format strings (#546). It might still be there for compatibility reasons but there is little reason to extend it to support writing to files, etc.
