### ISSUE TITLE
run time performance and build issue with C flags

### ISSUE THREAD

**Issue by toritesh** [fmtlib/fmt#3580]
We are build FMT 10.0 code using below command. 

cmake -DBUILD_SHARED_LIBS=FALSE -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_INSTALL_PREFIX=./fmt-10.0.0 -DCMAKE_C_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_C_FLAGS_RELEASE='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_CXX_FLAGS_RELEASE='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_C_COMPILER=gcc  -DCMAKE_CXX_COMPILER=g++

Generated libfmt.a has size 958878 and it does not give any runtime improvement or increase runtime of the testcase

But we use below command, 

cmake -DBUILD_SHARED_LIBS=FALSE -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_INSTALL_PREFIX=./fmt-10.0.0  -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_CXX_FLAGS_RELEASE='-D_GLIBCXX_USE_CXX11_ABI=0 ' -DCMAKE_C_COMPILER=gcc  -DCMAKE_CXX_COMPILER=g++

Generated libfmt.a has size 309960 and it gives good runtime improvement.

Could you let us know what is the issue with C flags ?

Thanks

**Comment by jaskij** [comment]
OP's slow variant adds two definitions:

```
-DCMAKE_C_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0 '
-DCMAKE_C_FLAGS_RELEASE='-D_GLIBCXX_USE_CXX11_ABI=0 '
```

which tell CMake to add the `_GLIBCXX_USE_CXX11_ABI` definition when calling the compiler.

Quoting [GCC manual](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)(emphasis mine)

> In the GCC 5.1 release libstdc++ introduced a new library ABI that includes new implementations of **`std::string`** and `std::list`. These changes were necessary to conform to the 2011 C++ standard which forbids Copy-On-Write strings and requires lists to keep track of their size.

My guess would be that something weird or wrong is going on because they are using a non-conformant `std::string` implementation. One that we don't know if GNU themselves are actually still working on, or just keep on life support.

@toritesh is there any reason to actually use those definitions? Do you need to link against such old libraries? Or is this simply a carryover from the past? Personally, I would just drop those definitions if you do not require them.

**Comment by vitaut** [comment]
Looks like you are overriding the default flags and as a result disabling all optimizations. You can check the actual build flags by turning the verbose CMake mode on.

**Comment by toritesh** [comment]
Thanks.

Issue resolved by -DCMAKE_CXX_FLAGS_RELEASE='-O3 -DNDEBUG
