### ISSUE TITLE
Consider adding version information to the main header file

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#411]
To allow client code rertieve library version instead of hard-coding it somewhere.

Motivation:
- informational purposes / troubleshooting (e. g. about box or log file with detailed list of used libraries)
- validation that code is being compiled with compatible version (e. g. if source is pulled from somewhere)

Can be in form of preprocessor definitions for integral version components (major, minor etc.) or preformatted string, e. g. "3.0.0". For example, [SQLite](sqlite.org) defines these macros:

    #define SQLITE_VERSION        "3.15.0"
    #define SQLITE_VERSION_NUMBER 3015000

**Comment by foonathan** [comment]
Good point.

@vitaut The version information is currently only available in CMake.
While it is easy to pass it to a C++ header, this requires an external CMake configuration step.
We could go the other way and parse the version from the header file, but I don't think the trouble is worth it compared to simply keeping two macros in sync.

**Comment by vitaut** [comment]
I am thinking of defining a single `FMT_VERSION` macro in the form

```c++
#define FMT_VERSION MMmmpp
```

as suggested for GCC [here](https://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html), where `MM` is a major version, `mm` is a minor version, and `pp` is a patch number, for example,

```c++
#define FMT_VERSION 030001
```
is version 3.0.1.

I think it is better than having separate major, minor, and patch macros because it requires awkward comparison:

```c++
/* Test for GCC > 3.2.0 */
          #if __GNUC__ > 3 || \
              (__GNUC__ == 3 && (__GNUC_MINOR__ > 2 || \
                                 (__GNUC_MINOR__ == 2 && \
                                  __GNUC_PATCHLEVEL__ > 0))
```
Major, minor, and patch version can be easily extracted from `FMT_VERSION`.

As for CMake, I think it's better to extract version from the header file to avoid duplication.

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/f5b1c16e2c1a8139885176cbd53a6d37bf9d006c.
