### ISSUE TITLE
Error in CMake build on MacOS with Clang

### ISSUE THREAD

**Issue by Khrysys** [fmtlib/fmt#4173]
I'm building a library that extensively uses fmt for it's debugging and error system, and on MacOS the build fails with the following error in my actions builds. The project uses C++20 and adds fmt as a subdirectory. It appears to be a clang specific problem.

```
/Users/runner/work/VkBootstrap3/VkBootstrap3/external/fmt/include/fmt/base.h:401:1: warning: unknown warning group '-Wbit-int-extension', ignored [-Wunknown-warning-option]
FMT_PRAGMA_CLANG(diagnostic ignored "-Wbit-int-extension")

/Users/runner/work/VkBootstrap3/VkBootstrap3/external/fmt/include/fmt/base.h:402:33: error: unknown type name '_BitInt'
template <int N> using bitint = _BitInt(N);
```

The error then seems to cascade down and cause many other errors in the file, but it appears to be centered around this one. I'm sure it's probably some error on my end, but multiple separate pieces have this error, so I'm not sure where it comes from.

**Comment by vitaut** [comment]
What clang version do you use? Could you provide a godbolt repro?

**Comment by Khrysys** [comment]
Clang version is 14.0.0.14000029. The error does not come from my own code, but from fmt's `src/format.cc`. That's the reason why I opened this instead of debugging my own things.

**Comment by vitaut** [comment]
clang 14 should support `_BitInt`: https://www.godbolt.org/z/bn7WaErG5. You might need to provide more repro details such as compiler flags.

**Comment by Arghnews** [comment]
My understanding: Apple clang is similar to but not the same as clang, and the version numbers while similar are apple's own. Ie. just because it works in llvm's clang 14 doesn't mean it will work in appleclang 14, as evidenced

Currently the `_BitInt` feature check is just

https://github.com/fmtlib/fmt/blob/891c9a73ae9a23ed8bffffb8753504b1f6f399d0/include/fmt/base.h#L396-L398

so we could expand it to rule out appleclang 14. I happen to have a macbook with apple clang: `Apple clang version 15.0.0 (clang-1500.1.0.2.5)` and can confirm `_BitInt` works fine there. On godbolt clang 13 doesn't support it, so maybe it's only appleclang 14. I'll put in a PR if this seems reasonable

@Khrysys you should be able to get round this error by defining `-DFMT_USE_BITINT=0` when building fmtlib to force `_BitInt` compilation to be disabled in the meantime

**Comment by Khrysys** [comment]
This seems like this should just be an easy, couple line PR then. I'll add that definition and see what happens when I get back home.

**Comment by vitaut** [comment]
I think we can bump clang requirement to 15. It's a very niche feature anyway.
