### ISSUE TITLE
Compilation error with AppleClang 16.0.0.16000026

### ISSUE THREAD

**Issue by indie-hub** [fmtlib/fmt#4181]
Hello, good people!

After updating XCode to version 16, fmt does not compile with the error below, on file `base.h`

```
error: constexpr variable 'sv' must be initialized by a constant expression
2670 |     FMT_CONSTEXPR auto sv = string_view(S());
```

Forcing `FMT_USE_CONSTEXPR = 0` solves the issue, but no `constexpr` are used.
With the previous version of AppleClang this was not an issue.

Could this be a compiler issue or just some compiler settings that should be set?
Thank you!

**Comment by ryouze** [comment]
Perhaps a bit unrelated, but I also encountered a problem after updating to macOS Sequoia 15.0 and `Clang 16.0.0 arm64-apple-darwin24.0.0`. **TLDR: Updating the C/C++ VSCode extension to `1.22.6 (pre-release)` fixed the problem for me.**

After updating macOS, I started seeing the following warning in VSCode for valid code that was nevertheless compiling and running correctly: `no instance of overloaded function "fmt::print" matches the argument list.`

![No instance of overloaded function](https://github.com/user-attachments/assets/00dd5969-ccca-419c-ac87-dbba6b24ad17)

Upon investigation, I discovered this was due to the `size()` method of `std::vector` returning `inline <error-type>` instead of `size_t`:

![Error type](https://github.com/user-attachments/assets/623d36fa-ced7-43dd-b39d-212ff9f18c4e)

After updating the C/C++ VSCode extension to the pre-release version `1.22.6 (pre-release)`, the `size()` method now correctly returns `size_t`, and the error no longer appears. Hope this helps someone facing a similar issue.

**Comment by vitaut** [comment]
@indie-hub, please provide the full error message and, if you get the error when compiling your code as opposed to the library itself, a repro.

**Comment by indie-hub** [comment]
@vitaut, thank you for your reply. I've been doing more testing and I can confirm that the library, per se, compiles flawlessly and the tests run.
Now, in my code, it compiles partially, meaning that there are some libraries of mine (which use fmt) that also compile without errors and others that do not compile. So it must be some issue with my CMake configuration somewhere along the path or related to my code.

```
In file included from /source/Core/Math/include/math/MathTypes.h:5:
In file included from /source/Core/Logger/include/logger/Logger.h:7:
In file included from /cmake-build-debug/_deps/fmt-src/include/fmt/core.h:5:
In file included from /cmake-build-debug/_deps/fmt-src/include/fmt/format.h:41:/cmake-build-debug/_deps/fmt-src/include/fmt/base.h:2670:24: error: constexpr variable 'sv' must be initialized by a constant expression
 2670 |     FMT_CONSTEXPR auto sv = string_view(S());
      |                        ^    ~~~~~~~~~~~~~~~~
/source/Core/Logger/include/logger/Logger.h:56:51: note: in instantiation of function template specialization 'fmt::fstring<std::string &>::fstring<std::string, 0>' requested here
   56 |         const std::string formatted = fmt::format(message, std::forward<Args>(args)...);
      |                                                   ^
/source/Core/Common/Profiling.h:80:9: note: in instantiation of function template specialization 'Logger::AssertLog<std::string &>' requested here
   80 |         LOGASSERT(!groupCallStack[m_group].empty(), "Stack is empty but \"{}\" profiler is still active", m_name)
      |         ^
/source/Core/Logger/include/logger/Logger.h:13:64: note: expanded from macro 'LOGASSERT'
   13 | #define LOGASSERT(condition, message, ...) Logger::Instance()->AssertLog(condition, message, __FILE__, __LINE__, ##__VA_ARGS__);
      |                                                                ^
/cmake-build-debug/_deps/fmt-src/include/fmt/base.h:2670:41: note: non-literal type 'std::string' cannot be used in a constant expression
```

thank you for your time.

**Comment by indie-hub** [comment]
hello, @vitaut. to further investigate this, I did a minimum test, which you can find below. Unfortunately, this does not compile, with the same error as above. 
Let me know if you want me to test anything further.

```
#include <iostream>
#include <fmt/format.h>

int main() {

    const std::string message {"Hello {}"};

    auto formatted_string = fmt::format(message, "World");
    std::cout << formatted_string;
}
```

**Comment by vitaut** [comment]
This is expected: format strings must be either known at compile time or wrapped in `fmt::runtime`, see https://fmt.dev/11.0/api/#compile-time-checks.
