### ISSUE TITLE
String width/alignment speed difference between v9.1.0 and v10.0.0-master

### ISSUE THREAD

**Issue by landshark666** [fmtlib/fmt#4227]
I was running some generic speed tests for a project between `fmt::format_to_n()` vs `snprintf()` and noticed the time for the same formatting was drastically different (more than 10x difference).  That didn't seem right so I started backing up in fmtlib versions to see if it was better in any previous versions, and it was.  Playing around on godbolt, something between v9.1.0 and v10.0.0 changed when formatting a string with width and alignment specifiers (`":<32s"`).

The compiler is set to GCC 11.4 because that's what I have access to at work.  However, I reproduces with 14.2 as well.

It's a dumb chrono-based timing so not very accurate, but the times still show ~3x longer from v10.0.0 onwards.

master: https://www.godbolt.org/z/d4hWfjE7M
v10.0.0: https://godbolt.org/z/68Ea6dMTx
v9.1.0: https://godbolt.org/z/eh94Pxaec

Is this expected?

**Comment by vitaut** [comment]
godbolt is not suitable for benchmarking for multiple reasons including the fact that it uses debug versions of libraries except the system libraries. So you are effectively comparing a debug version of {fmt} to optimized version of `snprintf`. Note that unlike `snprintf`, `format_to_n` correctly handles Unicode in width so it is expected to be slower on some inputs. It is a bit nuanced since {fmt} is generally faster on numeric formatting, which can offset the overhead for processing Unicode.

**Comment by landshark666** [comment]
FWIW, the code I have in the above issue is the same code I'm running on my dev system which is not using debug builds. I'm running 10 million iterations of each format style across 3 different fmtlib releases.

Here are the average times were from a handful of runs. The order of the data is v7.0.0, v7.1.3, v11.0.2. All times are ms, + or - ~25ms.

  - `{:<32}`  2899, 1996 3061
  - `{:32s}` 2900, 1989, 3029
  - `{:s}` 1644, 768, 522
  - `{}` 1241, 347, 366
  - c snprintf `-32s` 709
 
Sorry about the formatting, I'm typing this on my phone.

**Comment by landshark666** [comment]
> If you don't care about Unicode you can wrap string arguments in `fmt::bytes` which should be a bit faster.

Thank you. This cut the alignment+width formatting speed in half. Now v11.0.2 benchmarks the best amongst the 3 versions (I ended up making a series of Google benchmark tests for my scenarios).
