### ISSUE TITLE
Possible use-after-move in join()

### ISSUE THREAD

**Issue by mattgodbolt** [fmtlib/fmt#4231]
The code at:

https://github.com/fmtlib/fmt/blob/720da57baba83b3b1829e20133575e57aa1a8a4f/include/fmt/ranges.h#L661-L666

Does a
```cpp
auto it = std::forward<view_ref>(value).begin;
```

and later accesses `value.end` and `value.sep`.

In the case the iterator is _not_ copy constructible then the `view_ref` is an rvalue-reference:

```cpp
  using view_ref = conditional_t<std::is_copy_constructible<It>::value,
                                 const join_view<It, Sentinel, Char>&,
                                 join_view<It, Sentinel, Char>&&>;
```

which effectively turns the `forward<>` into a `move`.

`clang-tidy` warns on the accesses of `end` and `sep` as they are accesses on a moved-from object.

I'm not sure that this is _really_ a problem in practice but it seems like something that should be avoided. I can't see an easy way to do so though. I'm not sure we can cast _just_ the iterator easily? Taking a copy of `sep` works but for the same reasons as above we can't copy `end` out without a move either.

**Comment by mattgodbolt** [comment]
I'm a bit out of my depth but _maybe_ something like:
```cpp
    auto value_copy = std::forward<view_ref>(value);
    auto it = std::move(value_copy.begin);
    // rest of the code uses value_copy
```

**Comment by mattgodbolt** [comment]
CE link: https://compiler-explorer.com/z/8q9oj5v31

**Comment by Arghnews** [comment]
I had a look at this.

I believe this specialization is only used for exactly `fmt:join_view`s.

If you try and pass an lvalue `fmt::join_view`, you hit a static assert saying we can only pass rvalue views (https://compiler-explorer.com/z/9jjPodzzo)

So now we can be sure that this code path only deals with receiving `fmt::join`s that are rvalues.

This `format` function is called from here, line 2224:
https://github.com/fmtlib/fmt/blob/720da57baba83b3b1829e20133575e57aa1a8a4f/include/fmt/base.h#L2214-L2225

`qualified_type` on line 2220 in that block is always non const (for a `fmt::join_view`). See: 
https://compiler-explorer.com/z/cK3h3EzeP

This means that line 2224's first argument passed to `format` is:
`*static_cast<qualified_type*>(arg)` which will always deduce to `fmt::join_view&`

&nbsp;

A minimal fix is to change `fmt::join_view::format` to only take lvalues, since as it stands, that's all it will ever receive, and change `it` to `it&`:

```cpp
  template <typename FormatContext>
  auto format(join_view<It, Sentinel, Char>& value, FormatContext& ctx) const
      -> decltype(ctx.out()) {
    auto& it = value.begin;
```

This also saves a copy/move since we now take `it` by reference. The reference being into the original rvalue argument that is passed in the `println` call.

&nbsp;

Note this code was originally put in in [10508a30ecd91e5d09a27e4c6c0a01a89fd4edc7](https://github.com/fmtlib/fmt/commit/10508a30ecd91e5d09a27e4c6c0a01a89fd4edc7#diff-6ac6e767e83158d3347137b8f2ca90a37cb361e79c27fc3ba6a935074c26a342R635-R653) and changed to `std::forward` in [d2473b7b73c0af2a3ed34c99e50ace0a1040581a](https://github.com/fmtlib/fmt/commit/d2473b7b73c0af2a3ed34c99e50ace0a1040581a#diff-6ac6e767e83158d3347137b8f2ca90a37cb361e79c27fc3ba6a935074c26a342R639)

If I've missed anything or my assumptions or wrong, please point it out

&nbsp;

I can put in a PR for this if vitaut agrees this is a good change to make

**Comment by vitaut** [comment]
Thanks @mattgodbolt for reporting and @Arghnews for investigating the issue.

> A minimal fix is to change fmt::join_view::format to only take lvalues, since as it stands, that's all it will ever receive, and change it to it&

I think this is a correct fix.

> I can put in a PR for this if vitaut agrees this is a good change to make

Please do.

**Comment by mattgodbolt** [comment]
Thank you both!
