### ISSUE TITLE
Describe extension mechanism

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#489]
Need to document extension mechanism for supporting user-defined types. Currently the Extension section mentions `format_value` of the form:

```c++
void format_value(buffer& buf, const T& value, context& ctx);
```

but doesn't say what are the requirements for the implementations.

**Comment by manylegged** [comment]
Is there a natural way to forward the precision and other formatting operations to a custom formatter? For example, I would like to be able to say something like printf("{%.2f}", vec) where vec is a 3 element floating point vector type and get "{1.00, 0.00, 0.00}". 

Looking through the code it does not look like the "Spec" which contains the precision information is forwarded to the format_arg call, although it does not look too difficult to hack it in there for my own use.

**Comment by manylegged** [comment]
I was able to get vector formatting with inherited precision working but I had to modify the format_arg parameters slightly.  Basically I created a new class UserFormatter<ArgFormatter> which has a reference to the ArgFormatter (printf or the default one) instead of passing the BasicFormatter. UserFromatter forwards .writer() or .format() calls to the ArgFormatter, so it behaves as before. You can also call .visit() on it to format with the parsed FormatSpec. So the vector formatter looks like this (works for float/double/int vectors)

    template <typename ArgFormatter, typename T>
        void format_arg(fmt::UserFormatter<ArgFormatter> &f, const char *&format_str, const glm::tvec3<T> &vec)
        {
            typedef fmt::UserFormatter<ArgFormatter>::MakeArg Ar;
            f.visit(Ar(vec.x));
            f.writer() << ", ";
            f.visit(Ar(vec.y));
            f.writer() << ", ";
            f.visit(Ar(vec.z));
        }

Changes:
https://github.com/manylegged/fmt/commit/dacb973dac3a74d2d52e13661728b86f662b4004

I would submit a pull request but I wouldn't want to break backwards compatibility for everyone.

**Comment by vitaut** [comment]
> Is there a natural way to forward the precision and other formatting specifications to a custom formatter?

Unfortunately no, mainly because parsing of format specifiers depends on the argument type itself. For example, precision is allowed for floating-point types but not for integers. However, it might be possible to factor out the code that does parsing of standard format specs and reuse it. I'd recommend doing this instead of introducing another formatter class.

**Comment by vitaut** [comment]
Done, but need to document the default `format_value` that forwards to ostream `operator<<` and give an example of a custom `format_value`, possibly for time formatting.
