### ISSUE TITLE
No validation on number of arguments?

### ISSUE THREAD

**Issue by bryceschober** [fmtlib/fmt#492]
There doesn't seem to be any validation on the number of arguments passed matching the number in the format, at least in my usage of the writer api. Since fmtlib was advertised as a "safe" alternative to printf(), I guess I assumed that it would implement an equivalent of the compile-time checking of `-Wformat`, which does warn about argument count mismatches. Am I doing something wrong, or just expecting too much of fmtlib?

**Comment by vitaut** [comment]
Unfortunately compile-time checks are not supported although there are some tricks in #62 for printf formatting.

As for checking the arguments, the library follows Python's `str.format` conventions and reports an error when trying to access non-existent argument (or argument of a wrong type), but it's OK to pass more arguments than needed.

**Comment by foonathan** [comment]
Have you considered doing something with UDLs?

Like: `"Hello, {}!"_format` which creates a `format_str<1>` object containing the format string itself and the number of arguments. Then simply another `format()` overload accepting this objects that can do `static_assert()` with `sizeof...(Args)`. With C++14 constexpr it's pretty straightforward, with 11 also easy, just a little verbose and ugly.

**Comment by dean0x7d** [comment]
@foonathan Unfortunately, UDLs don't help here because there is no way to get type-system constants out of a `constexpr` function. The following seems like it should work, but it does not:

```c++
#include <type_traits>

constexpr auto operator""_size(char const*, std::size_t size) {
    return std::integral_constant<std::size_t, size>{};
    //                                         ^~~~
    // error: non-type template argument is not a constant expression
}

int main() {
    static_assert("hello"_size.value == 5, "");
}
```

The issue is that `constexpr` functions must be callable with either compiletime or runtime arguments, so no argument-dependent types can be generated. Up to and including C++17, the only way to get around this is by using macros... but it's as ugly as it sounds.

This could be solved if future standards allow overloading on the `constexpr`ness of the arguments or perhaps with static reflection (I haven't kept up with the reflection proposals, so I'm just guessing on the latter).

**Comment by foonathan** [comment]
There's a UDL version that takes the chars at non-type template argument... but not for string literals, damn it, you're right.

**Comment by vitaut** [comment]
Compile-time format string checks are now available: http://zverovich.net/2017/11/05/compile-time-format-strings.html

**Comment by fulara** [comment]
@vitaut but that does not solve mentioned issue right?
there is still no validation whether the number of {} matches the number of specified arguments, if they are without indices?
Should I create a issue/featurerequest for that? or is this behavior something you dont want at all?

**Comment by vitaut** [comment]
There is a validation in a sense that you cannot refer to nonexisting argument. Passing extra ones is OK as explained earlier.

**Comment by fulara** [comment]
Yes, and I dont see good reason why.
even printf provides warning:
```
<source>:8:22: warning: too many arguments for format [-Wformat-extra-args]
printf("%d", 1, 2);
```
Just today I had an issue where I passed extra one.. 

Can you please clarify whether this is concious decision or a limitation of the language? Because if you were able to achieve checking of {1} then I would hope that checking of argument could would be possible as well? :)

**Comment by vitaut** [comment]
> Can you please clarify whether this is concious decision or a limitation of the language?

This is a conscious decision. You can think of it as having unused arguments in a function - there are valid use cases for that. If we had a way of reporting warnings, it could be an opt-in warning as in `printf` case, but it shouldn't be a hard error.

**Comment by Folling** [comment]
It might be reasonable to provide a separate overload that performs this check, or perhaps even allowing the user to specify which checks he wants with a bitflag mechanism

**Comment by OleksandrKvl** [comment]
Recently I've adapted my company's internal logging class to `fmt`. Most team members are not familiar with it, for them (and for me too) it was very surprising to discover that one can miss format specifier and get no error even with compile-time checks. Consider that you have a log from some rarely visited branch which is never executed in a normal circumstances, the problem will be found too late.
This just doesn't make much sense to me, why should you follow conventions from another language? My logic is that if either format specifier or argument is provided, it must be processed, not ignored.
If a person provided an argument, it expects it to be in the output, otherwise it's a bug. You can apply exactly the same logic to `fmt::print("{} {}", "first");`, there are two format specifiers so person expected 2 things to be printed but only one is provided so you can just print nothing.

Oh god, I've just discovered the same is allowed for `std::format`...

**Comment by vitaut** [comment]
There are no plans to make this configurable but you can implement such a check (at least for simple cases because in general this feature may not be implementable) in your logging function.

**Comment by chrchr-github** [comment]
> Oh god, I've just discovered the same is allowed for `std::format`...
Oh god indeed.

> Update. Ok, I asked several people, read more comments and they convinced me that this behavior might be useful in some cases. Then maybe there can be some macro-flag to enable this specific check or another version of `FMT_STRING`?

Can you elaborate what those cases are?

**Comment by madscientist** [comment]
IMO, if you want good error messages for fmt you need to ask the compiler implementors (GCC and Clang) to create support for format string warnings in the compilers, just like printf format string checking is implemented by compilers not by the C runtime.  Since std::format exists now, it should definitely be something on their radar as a new attribute for example.

It's an amazing feat that fmt was able to generate the compile-time support that it has so far, and I tip my hat for sure, but there's just no way to get really useful, clear, concise, and warnings vs. errors, etc. for checking fmt strings without compiler support.

**Comment by vitaut** [comment]
This can be solved by providing a compile-time diagnostic reporting function in C++. Hardcoding format string parsing in the compiler doesn't make much sense and isn't even possible for UDTs.

**Comment by madscientist** [comment]
Sure that would be good too, especially if it were possible to allow the user to choose whether the diagnostic was considered fatal or not (-Werror).  But, we definitely want the ability to detect and notify the user if they provided TOO MANY arguments for the format string, not just too few arguments.  At least, we want the option to do that.  And it would be very nice if we could attach the checking attributes to the _declaration_ (as we can with attributes), not the invocation as we do today, so we don't need to litter the code with FMT_STRING macros.

**Comment by vitaut** [comment]
`FMT_STRING` is no longer needed for compilers that support `consteval`.
