### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by an-ky** [fmtlib/fmt#500]
Is it planned or does it collide with one of the libararies intent like speed and ease-of-use?

Best Regards

**Comment by vitaut** [comment]
What exactly do you mean by localization support in the context of this library? If you mean support for locale-specific formatting then it's already there (although can be improved), for example, there is `n` format specifier for locale-aware integer formatting.

**Comment by an-ky** [comment]
Sorry the question was a bit unspecific. Currently I'm replacing QStrings in our software

**Comment by an-ky** [comment]
Sorry, wrong button. I introduced fmtlib to replace QString.arg() and at some point boost.locale specific stuff and I wonderd whether there is a boost.locale.translate/QObject.tr equivalent to translate text by using some lookup mechanism. So the question is acutally less about localization but more about translation.

**Comment by vitaut** [comment]
Translation is out of scope of this library, but it should be possible to write such functionality on top of existing API because it's very easy to define your wrappers of formatting functions. You could probably do something like:

```c++
format_translated("The answer is {}.", 42);
```
where `format_translated` translates the format string and forwards it to `format`.
