### ISSUE TITLE
Error building on XCode

### ISSUE THREAD

**Issue by DJLink** [fmtlib/fmt#531]
Hello,

Sorry for the noob questions.
I had no issues compiling on Windows/Visual Studio, and works fine. but I was just moving to make some tests on Mac with Xcode and I can't get it to build, I get several errors like

string.h:20:52: No type named 'allocator' in namespace 'std'

I only added format.cc and format.h
Using libc++ (LLVM c++ standard lb with c++ 11 support).

If anyone could shine some light I would appreciate :)

Thanks

**Comment by vitaut** [comment]
You should include `fmt/format.h` not `format.h` and set include directories accordingly (point to the project directory and not the fmt subdirectory):

```c++
#include "fmt/format.h"
...
```

**Comment by DJLink** [comment]
Hi @vitaut 
Hum... strange that's actually what I have. 

#include "fmt/format.h"

![capture](https://user-images.githubusercontent.com/423769/27763856-c72c6428-5e83-11e7-9f9e-a337b3b9a37c.JPG)

**Comment by vitaut** [comment]
The include itself is not a problem, the include directories are. You should **not** add the directory containing `format.h` there (`-I` compiler option).

**Comment by vitaut** [comment]
If you do that, you can get the wrong header included and that's what happening here: `fmt/string.h` is included instead of system `string.h`. The naming `fmt/string.h` was a bit unfortunate but it's a general problem when header names clash. I added a better diagnostic in https://github.com/fmtlib/fmt/commit/c38170461d4fe6ebab775839d4d746a398c3844e.
