### ISSUE TITLE
Please add compile-time argument count checking

### ISSUE THREAD

**Issue by ksergey** [fmtlib/fmt#544]
Will be good if fmtlib will check number of arguments matched to number of arguments placeholders in format string.

**Comment by ksergey** [comment]
Something like there:
https://github.com/carlcook/variadicLogging/blob/master/main.cc

**Comment by vitaut** [comment]
Thanks for the suggestion, but note that the number of placeholders doesn't have to be the same as the number of arguments because there can be multiple placeholders referring to the same arguments:

```c++
fmt::format("{0}{0}", 42);
```

That said I plan to add a `constexpr` function for checking the format string. Will track it as a separate issue because it's part of the LEWG feedback.

**Comment by vitaut** [comment]
Adding `constexpr` checks is covered by #546.

**Comment by vitaut** [comment]
Compile-time format string checks are now available: http://zverovich.net/2017/11/05/compile-time-format-strings.html (note that it is still allowed not to use some arguments).
