### ISSUE TITLE
More info requested on pointer formatting

### ISSUE THREAD

**Issue by richard-fine** [fmtlib/fmt#557]
Hi,

I'm evaluating fmt and so far I'm really liking it :) but I've run into a use case we have that I'm not sure how to handle.

The comment in format.h about pointer formatting says:

```
  // The following two methods are private to disallow formatting of
  // arbitrary pointers. If you want to output a pointer cast it to
  // "void *" or "const void *". In particular, this forbids formatting
  // of "[const] volatile char *" which is printed as bool by iostreams.
  // Do not implement!
```

Could you elaborate on this a little bit?

We've got specific pointer types in our codebase that we'd like to define `format_arg` for. Casting them to `void*` won't work, as then we'd be defining `format_arg` for all pointers, rather than these specific ones, and we don't want to dereference the pointers as they're supposed to be treated more like opaque handles than actual pointers. So, the only option I see is to wrap them in something whenever they're being passed in, but it would be nice to eliminate that extra step (not least because the error message if you forget is not very helpful).

I don't quite understand the point about `iostream`; we're not using `iostream` in our codebase, so is it possible that this is protecting against something that doesn't actually affect us anyway?

**Comment by richard-fine** [comment]
Oh, and needless to say - I can just comment out those private declarations, declare my format_arg overload, and things _appear_ to work. But I don't know what I may be letting myself in for by doing this...

**Comment by vitaut** [comment]
> Could you elaborate on this a little bit?

This is basically done to prevent formatting when you accidentally pass a pointer instead of an object. For example,

```c++
  Foo foo;
  Foo *pfoo = &foo;
  auto s = fmt::format("{}", pfoo); // doesn't compile, possibly meant *pfoo
```

To resolve this you need to either explicitly cast it to a pointer if you want to format the pointer value:
```c++
  auto s = fmt::format("{}", static_cast<void*>(pfoo)); // formats pointer (e.g. "0x7fff54159a20")
```

or dereference the pointer to print the object itself:
```c++
  auto s = fmt::format("{}", *pfoo); // formats object itself
```

> I don't quite understand the point about iostream; we're not using iostream in our codebase, so is it possible that this is protecting against something that doesn't actually affect us anyway?

The part about ostream refers to a corner case 

```c++
const volatile char* s = "foo";
std::cout << s; // prints "1"
```
The comment just says that we forbid passing `const volatile char*` altogether, among other things.

> We've got specific pointer types in our codebase that we'd like to define `format_arg` for.

One way to make this work is to use SFINAE for the private declarations in question and disable them if an overload of `format_arg` is available. https://github.com/fmtlib/fmt/commit/01c5407d403371ddc8d07e8c12885c73ecf209c4 illustrates this although it requires a bit more work for C++98/03 compatibility. With this change you'll be able to do:

```c++
#include "fmt/format.h"

struct Foo {};

void format_arg(fmt::BasicFormatter<char> &f,
                const char *&format_str, const Foo *foo) {
  f.format("42");
}

int main() {
  Foo foo;
  Foo *pfoo = &foo;
  fmt::print("{}", pfoo); // prints "42"
}
```

Will this work for you?

**Comment by vitaut** [comment]
@richard-fine, are you still interested in this and do you want me to clean up and merge in https://github.com/fmtlib/fmt/commit/48466c354eb312782236ca5c5ce16619cea21357?

**Comment by richard-fine** [comment]
@vitaut Thanks, but we ended up going for a different solution (something more closely mimicking .NET format strings). So, don't merge it on my account. :)

**Comment by vitaut** [comment]
Thanks for the update.
