### ISSUE TITLE
Support error reporting with error_condition

### ISSUE THREAD

**Issue by eglimi** [fmtlib/fmt#566]
We recently started using fmtlib in a large embedded application. It uses `-fno-exceptions` and its own implementation of assert (for various reasons) that is always enabled. Therefore, the current error reporting strategy of using either exceptions or assert is not ideal for us, because any format failure means it crashes the application.

Versions of `format()` and `write()` that either use an `error_condition` or `error_code` for error reporting would therefore be great. Is there any interest in adding something like this to fmtlib?

**Comment by vitaut** [comment]
> Is there any interest in adding something like this to fmtlib?

Yes and the [`std` branch](https://github.com/fmtlib/fmt/tree/std) is moving in the direction of making this possible. Particularly, I plan to change 

```c++
template <typename Iterator, typename Handler>
Iterator parse_format_specs(Iterator it, Handler &handler);
```

to call `handler.on_error`, e.g.

```c++
handler.on_error("invalid fill character '{'");
```

instead of `FMT_THROW`:

```c++
FMT_THROW(format_error("invalid fill character '{'"));
```

and a similar mechanism to propagate an error up to the formatting function where it can be handled in a different ways, either by throwing an exception or by returning an error code without relying on macros.

**Comment by vitaut** [comment]
Compile-time format string checks and `format_to_n`/iterator support make error-code-based API largely unnecessary.
