### ISSUE TITLE
output is out of order

### ISSUE THREAD

**Issue by baiwfg2** [fmtlib/fmt#576]
Hi.

```
	fmt::MemoryWriter w;
	w.write("Look, a {} string", 'C');
	fmt::print(w.str()); // returns a C string (const char*)

	fmt::print(stderr, "System error code = {}\n", 0);
```
If I write code like this, the output is consistently like this:

> System error code = 0
> Look, a C string

Why is that ? stdout won't behave like this. Even it's line-buffered, it shouldn't invert the order.

**Comment by foonathan** [comment]
Given that `fmt::print` is just an `fwrite()`, I don't think its format's fault.

I couldn't reproduce it on my system either, so I assume this is a buffer issue on your system.

**Comment by Mandar12** [comment]
The issue is reproducible for me. The observed output is because of writing to stdout and stderr. [https://unix.stackexchange.com/questions/206224/stderr-gets-flushed-before-stdout-when-using-file-logger](url)
By default, stdout is line buffered, stderr is none buffered and file is completely buffered.

**Comment by baiwfg2** [comment]
@Mandar12 I see. Thanks.
