### ISSUE TITLE
Enhancement: provide custom locale to fmt::format

### ISSUE THREAD

**Issue by kivadiu** [fmtlib/fmt#597]
The library is extremely useful so that I would like to use it everywhere but it uses snprintf to print floats which uses the global locale.

One problem is when the global locale is set to a language specific locale and you still want to write some numbers with the C locale. Or you may just want to write with different locales in the same program.

Changing the global locale when you call `fmt::format` is not thread safe, so:
1. is there a solution today to force the C locale in `fmt::format` if the global locale is different?
2. if not, would it be possible to have something like `fmt::format(locale_name, "format", arg1, arg2, ...);`
but I guess this would mean to rewrite snprintf?

**Comment by vitaut** [comment]
The std branch of the library allows passing a locale via a buffer. Unfortunately it doesn't solve the  issue with formatting of floating-point numbers because they are formatted with `snprintf` which uses the global locale. To solve this we need a custom implementation of floating-point formatting (#147). Note that formatting of integers is already locale-independent.

**Comment by foonathan** [comment]
A couple of years ago I wrote such an implementation, I can look tomorrow whether I can find it

**Comment by kivadiu** [comment]
Could we copy the implementation of snprintf from the GNU libc?

**Comment by beojan** [comment]
No, fmt is BSD licensed. I suppose you could copy it from BSD libc, if you *really* wanted.

**Comment by vitaut** [comment]
Closing in favor of #147, since the problem is in floating-point formatting not locale itself.
