### ISSUE TITLE
Please make BUILD_SHARED_LIBS a cmake option

### ISSUE THREAD

**Issue by yurivict** [fmtlib/fmt#600]
Also, please add a separate option to build a static library (it is a default now).

**Comment by vitaut** [comment]
Why do you need to make `BUILD_SHARED_LIBS` an option?

**Comment by yurivict** [comment]
So that when people look what options does this project have, they will see it. Otherwise, it is buried somewhere deep inside.

**Comment by vitaut** [comment]
`BUILD_SHARED_LIBS` is a standard CMake option and there is little reason to build fmt as a shared library, so I don't see much value in making it an option only for visibility sake.

**Comment by beojan** [comment]
Apart from the Cling issue (#596). Maybe the default could be to build both static and shared libs?

**Comment by vitaut** [comment]
> Maybe the default could be to build both static and shared libs?

This will add overhead for everyone whether they use static or shared library, so I'd rather avoid this configuration.

The cling issue seems pretty unusual, normally you'd want to use the static library. However building the shared library is documented in http://fmtlib.net/latest/usage.html#building-the-library and `BUILD_SHARED_LIBS` is a standard CMake way of doing it.

**Comment by yurivict** [comment]
> normally you'd want to use the static library

No, normally systems should use shared library, unless there are reasons to use static library.

**Comment by vitaut** [comment]
In any case, switching between the two is super easy and documented, but if there is more to it I'd be happy to accept a PR.

**Comment by W4RH4WK** [comment]
Hey. I am currently running into this as I am using fmt as part of a library (and also exposing fmt from that library). I'd like to build fmt as a static library, but don't want to touch the global `BUILD_SHARED_LIBS`.

More specifically, in our setup, we are including fmt's `CMakeLists.txt` directly using `add_subdirectory`; we plan to do the same with the library we are currently building. We prefer this way since it's simpler than dealing with ExternalProject / FetchContent. However, this way everything uses the same global scope. So we'd prefer to configure fmt directly to build either as a static or shared library.

Adding an option `FMT_BUILD_SHARED` which defaults to `${BUILD_SHARED_LIBS}` should do the trick.
As reference, [zstd has similar options](https://github.com/facebook/zstd/blob/4dfaf0003f8619306aecbaf9bd79733e27a828c5/build/cmake/lib/CMakeLists.txt#L14).

**Comment by vitaut** [comment]
I think you should be able to set `BUILD_SHARED_LIBS` before `add_subdirectory`. Does it solve the problem?

**Comment by phprus** [comment]
@vitaut 
If you have a complex dependency graph, you may need to change **and revert** the value of ``BUILD_SHARED_LIBS`` variable frequently.

**Comment by vitaut** [comment]
Sure but if you need to do this more than once you could put this logic into a trivial CMake function/macro. Or even better group all vendored libraries that need to be built statically together and set/unset `BUILD_SHARED_LIBS` once for the whole group. This is probably better than having to set a bunch of nonstandard library-specific variables.
