### ISSUE TITLE
Use ideas from jeaiii's itoa to further optimize integer formatting

### ISSUE THREAD

**Issue by vitaut** [fmtlib/fmt#625]
https://github.com/miloyip/itoa-benchmark/blob/master/src/itoa_jeaiii.cpp

**Comment by vitaut** [comment]
Done in https://github.com/fmtlib/fmt/commit/e37151021e1028837d2e981af51d32d31b456478. Need to integrate and benchmark.

**Comment by vitaut** [comment]
There are faster methods than jeaiii for non-uniform data (different number of digits):

![jeaiii](https://user-images.githubusercontent.com/576385/37721517-f9342f5a-2ce6-11e8-8ea7-8cf02c46e30f.jpg)

**Comment by jeaiii** [comment]
Hi, thanks for taking the time to look at itoa_jeaiii.  Are those results from the miloyip benchmark? And on what system/toolchain? As is, that benchmark program was very sensitive to the order in which the functions were called. I ended up making many changes to get stable results. My results are at https://jeaiii.github.io/itoa/ for vs2017/x86_64. The first column with the '?' is for random values. I believe "amartin" didn't do well in my results because the compiler didn't optimize it well, but the rest seem reasonable.

**Comment by vitaut** [comment]
> Are those results from the miloyip benchmark?

Yes.

> And on what system/toolchain?

macOS+clang IIRC

> I ended up making many changes to get stable results.

Where can I find the updated benchmark? Did you submit the changes upstream?

**Comment by jeaiii** [comment]
I updated jeaiii/itoa-benchmark , very much a work in progress...windows only.
outputs to json now, for use with highcharts. see index.html
