### ISSUE TITLE
basic_string<...> instead of string and wstring

### ISSUE THREAD

**Issue by swex** [fmtlib/fmt#629]
Hello!
Just wonder why don't use basic_string instead of  wstring and string?

**Comment by vitaut** [comment]
If you mean the `format` functions, then overloads are used instead of parametrization on char type to allow implicit conversions. For example, the following code doesn't work:

```c++
template <typename Char, typename... Args>
std::basic_string<Char> format(std::basic_string_view<Char>, Args...);

format("{}", 42);
```

while this does:

```c++
template <typename... Args>
std::string format(std::string_view, Args...);

format("{}", 42);
```

In most other cases, `std::basic_string` is used and it is easy to add `format` overloads for exotic char types.
