### ISSUE TITLE
Are positional arguments not checked at compile time?

### ISSUE THREAD

**Issue by agauniyal** [fmtlib/fmt#667]
For example - https://godbolt.org/g/DUSJ4h

**Comment by vitaut** [comment]
They are but in limited contexts right now, because of the issues outlined in http://fmtlib.net/Text%20Formatting.html#CompileTimeFormat. For example

```c++
#include "fmt/format.h"

int main() {
    using namespace fmt::literals;
    "The number is: {10}"_format("Helllllluuuuuuuuu");
}
```
will give you a compile-time error which will include among other things

```
       context_.on_error("argument index out of range");
       ^~~~~~~~
```

See https://godbolt.org/g/sW8AhP.

Eventually the checks will apply to all APIs.

**Comment by vitaut** [comment]
I've added an overload of `print` with a constexpr format string check, so this gives a compile-time error now:

```c++
#include <fmt/format.h>

int main() {
  fmt::print(FMT_STRING("The number is: {10}"), "Helllllluuuuuuuuu");
}
```

Note that you need to wrap the format string in `FMT_STRING` to make it a compile-time string.
