### ISSUE TITLE
silent skip of invalid format when a compiler error is desired

### ISSUE THREAD

**Issue by blakehawkins** [fmtlib/fmt#670]
I hope you don't mind if I just link to the issue I created on spdlog! https://github.com/gabime/spdlog/issues/614

I don't have an MWE - please let me know if that's problematic.

**Comment by vitaut** [comment]
{fmt} throws an exception in case of an invalid format, for example:

```c++
#include <fmt/core.h>

int main() {
  fmt::format("{:x}", "foo");
}
```
will give something like
```
libc++abi.dylib: terminating with uncaught exception of type fmt::format_error: invalid type specifier
```
The exception is probably caught in spdlog and that's why it appears that the output is skipped (although it might be worth logging an error instead, cc @gabime).

Compile-time format string checks will be available in the next major version.
