### ISSUE TITLE
Curry style for string format call

### ISSUE THREAD

**Issue by slonm** [fmtlib/fmt#740]
Hi Victor,
I have been started use fmtlib long time ago (assume since some v0.x.x). In those days the style of the call was:
`std::string message = fmt::str(fmt::Format("The answer is {}") << 42);
fmt::Print("The answer is {}") << 42;`

I don't like chevrons. I found that's one is not graceful and after some experiments came to following:
```cpp
//Added "fmt::Formatter& operator()(Arg arg)" with same behavior like fmt::Formatter& operator<<(Arg arg)
//implicit formatting call and conversion to std::string via call "operator std::string()"
std::string message = fmt::Format("The answer is {}")(42);

//Construct string in several steps
auto formatter = fmt::Format("a={} b={}");
formatter(1);
formatter(2);
std::string message = formatter();

//explicit formatting call and conversion to std::string via "std::string operator()()" call
boost::filesystem::path dir = fmt::Format("/usr/{}")("bin")(); 

//Just alias for fmt::Format
std::string message = SS("The answer is {}")(42);`

//Print to stdout with line break
fmt::PrintLn("The answer is {}")(42);
```
All this is done via simple additional operators to Formatter class and free functions.

This days i wanted upgrade fmtlib in my project and found no trivial ways to implement currying stile for arguments. 
I would like to use the libfmt capabilities of the moderm syntax, but not overwrite the existing code.
It's may be done with some wrapper for partial application like [Элементы функционального программирования в C++: частичное применение](https://habr.com/post/313370/) but will be good found the way for internal implementation as before. Could you give some suggestion howto do it?

Thanks Mihail

**Comment by vitaut** [comment]
One way of doing this is to implement an argument list builder (`format_arg_builder`) that is similar to [`format_arg_store`](https://github.com/fmtlib/fmt/blob/master/include/fmt/core.h#L974) but allows to add arguments incrementally instead of all at once. Then you can write a functions that returns the format string and the builder wrapped in an object that provides your desired API:

```c++
struct incremental_formatter {
  std::string format_str;
  format_arg_builder builder;

  template <typename T>
  void operator()(const T& value) { builder.push_back(value); }

  std::string operator()() { return fmt::vformat(format_str, builder.format_args()); }
};

incremental_formatter format(const char *format_str) {
  return {format_str, format_arg_builder()};
}
```

This won't be very efficient though (at least if you want to make such an API safe) because you'll have to copy arguments and the format string to guarantee that they are alive at the formatting time. This is one of the reasons Boost Format which follows this approach is [so spectacularly slow](https://github.com/fmtlib/fmt#speed-tests).
