### ISSUE TITLE
Hardcoded headers path in *.cc files

### ISSUE THREAD

**Issue by alabuzhev** [fmtlib/fmt#745]
format.cc and posix.cc now expect headers to be in "fmt/" subdirectory.
Is it intentional? Now instead of simply putting all fmt files somewhere and adding that directory to include one must replicate the directory structure. Not a big deal of course, but is it necessary?

**Comment by vitaut** [comment]
> Is it intentional?

Yes, the canonical paths for fmt header files are `fmt/*.h` which reduces the chance of collision with system headers (which occurred in the past) because `fmt` acts as a namespace of sorts.

> Not a big deal of course, but is it necessary?

Not strictly necessary, but without this we'd have to add `include/fmt` to the search paths which is undesirable for the reason mentioned above. It is also nice to use the same includes in the library code that are recommended for the user code for consistency reasons.

**Comment by alabuzhev** [comment]
Thanks for the explanation.

> collision with system headers (which occurred in the past)

Actually it is still there: format-inl.h has `#include "locale.h"`, and implementations are [allowed](http://en.cppreference.com/w/cpp/preprocessor/include) to pick a deprecated version of [clocale](http://en.cppreference.com/w/cpp/header/clocale) instead, if there's no locale.h in the same directory (which can happen if one thinks that it's an optional part of the library).

**Comment by vitaut** [comment]
Good catch, thanks! I merged `locale.h` into `format-inl.h` in https://github.com/fmtlib/fmt/commit/6ebc1a967d9a54f8209b3c415039aff3979dd762.
