### ISSUE TITLE
Include single header file

### ISSUE THREAD

**Issue by Stannieman** [fmtlib/fmt#866]
Hi Victor

Could you consider also providing a single header .hpp file like other projects do?
In versions older than 5.x there were just 1 .cc and 1 .h file and it was no problem, but now there are more files and it would be more convenient if there was only 1. I have no experience with generating this kind of file myself but I assume it can be done in 1 simple build step.

Regards
Stan

**Comment by vitaut** [comment]
Could you elaborate why do you think this would be more convenient than having several headers?

**Comment by Stannieman** [comment]
![capture](https://user-images.githubusercontent.com/1538156/45635012-2f8d6a80-baa4-11e8-9c5c-9fac9f3b65de.PNG)
Right now I manage my dependencies like this. IMO this is cleaner than having to maintain multiple files in a separate directory for every dependency. Plus there would be the risk that I accidentally forget to update 1 of the files at some point. With a single file there is no such risk.

**Comment by vitaut** [comment]
fmt headers should be located in a directory called `fmt` and included with the directory prefix, e.g. `fmt/format.h`. The unprefixed use is discouraged due to potential ambiguity. Moreover in version 5, you just need 3 files, `format.h`, `format-inl.h`, and `core.h`, in header-only mode which is not a big difference from the 2 files required in version 4.

**Comment by Stannieman** [comment]
Ok thanks, 3 files is still reasonable. I thought all of them were needed.
