### ISSUE TITLE
Inconsistent warning flags specified in CMakeLists.txt for different compilers (possibly by mistake)

### ISSUE THREAD

**Issue by nyronium** [fmtlib/fmt#928]
While skimming through the `CMakeLists.txt`, I found that several warning flags have inconsistent (opposite) values for gcc and clang, which seems to be a mistake (please elaborate if I'm wrong).

#### First inconsistency `-Wzero-as-null-pointer-constant`

For gcc, `-Wzero-as-null-pointer-constant` is explicitly enabled if the host uses gcc >= 5.0,
while for clang `-Wno-zero-as-null-pointer-constant` (Note the **`-Wno-`**) is set and therefore the warning is disabled.

#### Second inconsistency `-Wshadow`

Also in gcc's `PEDANTIC_COMPILE_FLAGS`, `-Wshadow` is followed by `-Wno-shadow`:

```cmake
set(PEDANTIC_COMPILE_FLAGS -pedantic-errors -Wall -Wextra -pedantic
    -Wold-style-cast -Wundef
    -Wredundant-decls -Wshadow [...] -Wno-shadow)
```

#### Other issues

Possibly there are other inconsistencies or mistakes, but as the authors intent does not appear clearly to me, I am unable to further judge the other flags.
I just wanted to point out, that almost every flag passed to clang is prefixed with `-Wno-`, and as `-Wno-zero-as-null-pointer-constant` appears to be a mistake, it might be worth having a look at the other flags, too.

**Comment by eliaskosunen** [comment]
I was the one that wrote those flags, see #736.

[See git blame for CMakeLists.txt for the commit that introduced these changes](https://github.com/fmtlib/fmt/blame/699297520a50cd92959a3f00579b3172ee9229d4/CMakeLists.txt#L69-L114). You can see, that gcc follows the scheme of enabling every flag possible, while clang uses `-Weverything` and then disables some of the noisier warnings.

**Point 1:**
I honestly don't remember what was my reasoning behind this, but it looks like a honest mistake. That warning should be enabled on both gcc and clang, and I can't think of any reason to disable it on clang, given that it's also enabled on gcc.

**Point 2:**
This was changed later [here]{https://github.com/fmtlib/fmt/commit/479ee2a8c610728f509ac6a2038aa9d31c3b79d5#diff-af3b638bc2a3e6c650974192a53c7291R72}, I don't know why the change was done nor why it was done this way instead of simply removing the flag.

**Comment by nyronium** [comment]
Fair enough. Although I cannot find that `-Weverything` is being used here, only `-Wall` for both compilers.

**Comment by eliaskosunen** [comment]
See the blame from my previous comment. Line 96 has `-Weverything`. This was rather sloppily changed in `50b18a`, without removing the `-Wno`s.

**Comment by vitaut** [comment]
Looks like I accidentally messed up the warnings. Should be cleaned in https://github.com/fmtlib/fmt/commit/34030deca9e64ef0523eff48993fc028d01df1fe.
